package com.lsh.testing05.joborder.vo;

import java.sql.Time;
import java.util.Date;

public class JoborderVO {
	
	public String[] JOBORDER_PROCESS_CUSTOMERNAME2;
	
	public String[] getJOBORDER_PROCESS_CUSTOMERNAME2() {
		return JOBORDER_PROCESS_CUSTOMERNAME2;
	}
	public void setJOBORDER_PROCESS_CUSTOMERNAME2(String[] jOBORDER_PROCESS_CUSTOMERNAME2) {
		JOBORDER_PROCESS_CUSTOMERNAME2 = jOBORDER_PROCESS_CUSTOMERNAME2;
	}
	
	public String CONVERT_JOBORDER_PROCESS_PLANENDDAY;
	
	public String[] CONVERT_JOBORDER_PROCESS_PLANENDDAY2;
	
	public String[] getCONVERT_JOBORDER_PROCESS_PLANENDDAY2() {
		return CONVERT_JOBORDER_PROCESS_PLANENDDAY2;
	}
	public void setCONVERT_JOBORDER_PROCESS_PLANENDDAY2(String[] cONVERT_JOBORDER_PROCESS_PLANENDDAY2) {
		CONVERT_JOBORDER_PROCESS_PLANENDDAY2 = cONVERT_JOBORDER_PROCESS_PLANENDDAY2;
	}
	public String getCONVERT_JOBORDER_PROCESS_PLANENDDAY() {
		return CONVERT_JOBORDER_PROCESS_PLANENDDAY;
	}
	public void setCONVERT_JOBORDER_PROCESS_PLANENDDAY(String cONVERT_JOBORDER_PROCESS_PLANENDDAY) {
		CONVERT_JOBORDER_PROCESS_PLANENDDAY = cONVERT_JOBORDER_PROCESS_PLANENDDAY;
	}

	public Date JOBORDER_PROCESS_PLANENDDAY;
	public Date[] JOBORDER_PROCESS_PLANENDDAY2;
	
	public Date getJOBORDER_PROCESS_PLANENDDAY() {
		return JOBORDER_PROCESS_PLANENDDAY;
	}
	public void setJOBORDER_PROCESS_PLANENDDAY(Date jOBORDER_PROCESS_PLANENDDAY) {
		JOBORDER_PROCESS_PLANENDDAY = jOBORDER_PROCESS_PLANENDDAY;
	}
	public Date[] getJOBORDER_PROCESS_PLANENDDAY2() {
		return JOBORDER_PROCESS_PLANENDDAY2;
	}
	public void setJOBORDER_PROCESS_PLANENDDAY2(Date[] jOBORDER_PROCESS_PLANENDDAY2) {
		JOBORDER_PROCESS_PLANENDDAY2 = jOBORDER_PROCESS_PLANENDDAY2;
	}


	public Integer USE_ON;
	
	public Integer getUSE_ON() {
		return USE_ON;
	}
	public void setUSE_ON(Integer uSE_ON) {
		USE_ON = uSE_ON;
	}
	
	
	public String JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK;
	public String[] JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2;
	
	public String PROCESS_MAIN_CATEGORY_NAME;
	
	//원본설비용
	public int ORIGIN_EQUIPMENT_ID;
	public String ORIGIN_EQUIPMENT_NAME;
	public String ORIGIN_EQUIPMENT_MODELNAME;
	public String ORIGIN_EQUIPMENT_CONTEXT;
	
	public String EQUIPMENT_SENSOR_MATCHING_NUMBER;
	
	//프리셋 검색용 명칭
	public String SETTING_PRESET_NAME;
	
	//모니터링 용
	public int JOBORDER_SALES;
	public int JOBORDER_INDUSTRY;
	
	//ProjectJobNo용
	public int MAX_VALUE;
	
	public int PROCESS_VALUES;
	
	public int TOTAL_NOT_PROCEED;
	
	//Home1용
	public int TOTAL_JOBORDER;
	public int TOTAL_COMPLETE;
	public int TOTAL_PROCEED;
	
	//Home2용
	public int BADQUANTITY;
	
	//home3용
	public int OUTSOURCING;
	
	//조회용 BOM 추가
	public String BOM_LIST_MAIN_PRODUCTCODE;
	public String BOM_LIST_MAIN_NAME;
	public int BOM_LIST_QUANTITY;
	
	public String BOM_DETAIL_DIVISION;
	
	public float BOM_DETAIL_C_ID;
	public float BOM_DETAIL_OD;
	public float BOM_DETAIL_MATERIALTHICK;
	public String BOM_DETAIL_MATERIAL;
	
	
	
	//로그 사용시 구분값들
	public int LOG_TB_ID;
	
	//곱하기 계산 계획 수량
	public int PLAN_QUANTITY;
	
	//작업지시서 통합 자주검사서식
	public String JOBORDER_INSPECTIONFILE;
	
	//세팅프리셋 파일 조회용
	public int SETTING_PRESET_FILE_MANAGEMENT_ID;
	public Integer SETTING_PRESET_ID;
	public String SETTING_PRESET_FILE_MANAGEMENT_NAME;
	public String SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	public String SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;

	public int[] SETTING_PRESET_FILE_MANAGEMENT_ID2;
	
	//납기일
	public String DEL_firstday;
	public String DEL_secondday;
	//배포일
	public String PUB_firsday;
	public String PUB_secondday;
	
	//조회 변수를 위한 것들
	public String BOM_DETAIL_PRODUCTCODE;
	public String BOM_DETAIL_BELLOWSCODE;
	public String JOBORDER_EMERGENCY_STATUS_NAME;
	public int CT_FILE_REGISTER_DRAWING;
	public String JOBORDER_STATUS_NAME;
	
	//작업자 첨부파일 변수
	public int JOBORDER_PROCESS_FILE_MANAGEMENT_ID;
	public int[] JOBORDER_PROCESS_FILE_MANAGEMENT_ID2;
	

	public String JOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME;
	public String JOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY;
	
	//작업지시서 공정 이력
	public int JOBORDER_PROCESS_STATUS_ID1;
	public int JOBORDER_PROCESS_STATUS_ID2;
	public Date JOBORDER_PROCESS_RESULT_STARTTIME;
	public Date JOBORDER_PROCESS_RESULT_ENDTIME;
	public int JOBORDER_PROCESS_RESULT_RUNTIME;
	
	//공정 결과 정보 서식
	public int PROCESS_RESULT_TEMPLATE_ID;
	public String PROCESS_RESULT_TEMPLATE_QUANTITY;
	public String PROCESS_RESULT_TEMPLATE_BADCODE;
	public String PROCESS_RESULT_TEMPLATE_BADQUANTITY;
	public String PROCESS_RESULT_TEMPLATE_GOODQUANTITY;
	
	//작업지시서 공정 수정이력
	public int JOBORDER_PROCESS_REVISE_ID;
	public String JOBORDER_PROCESS_REVISE_CONTEXT;
	public String[] JOBORDER_PROCESS_REVISE_CONTEXT2;
	
	public Date JOBORDER_PROCESS_REVISE_TIME;
	
	//작업지시서 공정 중지이력
	public String JOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME;
	public String JOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER;
	public String JOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT;
	public Date JOBORDER_PROCESS_STOPRESULT_STOPTIME;
	public Date JOBORDER_PROCESS_STOPRESULT_RESTARTTIME;
	public int JOBORDER_PROCESS_STOPRESULT_ID;
	
	//작업지시서 공정 변수
	public int JOBORDER_PROCESS_ID;
	
	public int[] JOBORDER_PROCESS_ID2;
	
	public int PROCESS_MAIN_CATEGORY_ID;
	public int JOBORDER_FORM_DETAIL_ID;
	public int JOBORDER_PROCESS_RESULT_ID;
	public int JOBORDER_PROCESS_STATUS_ID;
	public String JOBORDER_PROCESS_NAME;
	
	public String JOBORDER_PROCESS_STATUS_NAME;
	
	public int JOBORDER_PROCESS_INDEX;
	public int[] JOBORDER_PROCESS_INDEX2;
	
	public int JOBORDER_PROCESS_FOCUSON;
	
	public float JOBORDER_PROCESS_WORKTIME;
	public float[] JOBORDER_PROCESS_WORKTIME2;
	
	public String JOBORDER_PROCESS_SELFINSPECT_FILE;
	public String[] JOBORDER_PROCESS_SELFINSPECT_FILE2;
	
	public String JOBORDER_PRCOESS_FILE;
	public Date JOBORDER_PROCESS_STARTDAY;
	public Date JOBORDER_PROCESS_ENDDAY;
	public int JOBORDER_PROCESS_OUTSOURCING;

	public String JOBORDER_PROCESS_CUSTOMERNAME;
	public String JOBORDER_PROCESS_CUSTOMERNUMBER;

	public float JOBORDER_PROCESS_RUNNIGTIME;
	
	//시간 초과 변수
	public int JOBORDER_PROCESS_WORKOUT;
	
	//작업지시서 설비 변수
	public int JOBORDER_EQUIPMENT_ID;
	public String JOBORDER_EQUIPMENTNAME;
	public String JOBORDER_EQUIPMENTMODELNAME;
	public String JOBORDER_EQUIPMENTCONTEXT;
	public int JOBORDER_EQUIPMENTUSEON;
	
	//원본 공정 변수
	public String ORIGIN_PROCESS_NAME;
	public String ORIGIN_PROCESS_CODE;
	
	public int ORIGIN_PROCESS_ID;
	public int[] ORIGIN_PROCESS_ID2;
	
	public int ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	public String ORIGIN_PROCESS_CUSTOMER_NAME;
	public String ORIGIN_PROCESS_CUSTOMER_NUMBER;
	
	//작업지시서 특이사항 변수
	public int JOBORDER_UNIQUESS_ID;
	public int[] JOBORDER_UNIQUESS_ID2;

	public String JOBORDER_UNIQUESS_CONTEXT;
	public String[] JOBORDER_UNIQUESS_CONTEXT2;
	public String[][] JOBORDER_UNIQUESS_CONTEXT3;
	
	//작업지시서 QR 파일 변수
	public int QRCODE_ID;
	public String QRCODE_DIRECTORY;
	
	//작업지시서 파일 변수
	public int JOBORDER_FILE_MANAGEMENT_ID;
	public int[] JOBORDER_FILE_MANAGEMENT_ID2;
	
	public int JOBORDER_FILE_TYPE_ID;
	public int[] JOBORDER_FILE_TYPE_ID2;
	public String JOBORDER_FILE_MANAGEMENT_NAME;
	public String JOBORDER_FILE_MANAGEMENT_DIRECTORY;
	
	//작업지시서 TB 변수
	public int JOBORDER_ID;
	public int JOBORDER_LOBBY_ACTIVITY_ID;
	
	public int JOBORDER_LOBBY_ACTIVITY_ID1;
	public int JOBORDER_LOBBY_ACTIVITY_ID2;
	public int JOBORDER_LOBBY_ACTIVITY_ID3;
	
	public int JOBORDER_EMERGENCY_ID;
	public int CT_FILE_REGISTER_ID;
	public int JOBORDER_STATUS_ID;
	public int ORIGIN_ACCOUNT_ID;
	public int BOM_DETAIL_ID;
	public int BOM_LIST_ID;
	public Integer JOBORDER_PUBLISH;
	public String JOBORDER_CODEFILE;
	public String JOBORDER_WORKINSPECTIONFILE;
	
	public Date JOBORDER_PUBLISHDAY;
	public Date JOBORDER_STARTDAY;
	public Date JOBORDER_ENDDAY;
	
	public String JOBORDER_CONTEXT;
	
	//작업자 이름 변수
	public String ORIGIN_ACCOUNT_MEMBERNAME;
	
	//작업지시서 서브 타이틀 변수
	public int JOBORDER_SUBTITLE_ID;
	public String JOBORDER_SUBTITLE_NAME;
	public int JOBORDER_SUBTITLE_DIVISION;
	
	//작업지시서 디테일 BOM 변수
	public int JOBORDER_DETAIL_ID;
	
	//작업지시서 상세정보 사업명 / 사업명
	public String JOBORDER_DETAIL_BUSINESSNAME;
	
	//작업지시서 상세정보 품명 / 도면명
	public String JOBORDER_DETAIL_PRODUCTNAME;
	
	//작업지시서 상세정보 수량 / 제작 수량
	public int JOBORDER_DETAIL_QUANTITY;
	
	//작업지시서 상세정보 납품처 / 고객
	public String JOBORDER_DETAIL_CLIENT;
	
	//작업지시서 상세정보 납기 / 납기 => Date 형식에 맞게 변환해서 넣어야함
	public Date JOBORDER_DETAIL_DEILVERYDAY;
	public String CONVERT_JOBORDER_DETAIL_DEILVERYDAY;
	
	//작업지시서 상세정보 작업지시번호 / 작업지시번호
	public String JOBORDER_DETAIL_JOBNUMBER;
	
	//작업지시서 상세정보 완료품목코드(품번)/도면번호)
	public String JOBORDER_DETAIL_PRODUCTNUMBER;
	
	//작업지시서 상세정보_사이즈
	public int JOBORDER_DETAIL_SIZE;
	
	//작업지시서 상세정보_샤링폭
	public float JOBORDER_DETAIL_SHEARINGWIDTH;
	
	//작업지시서 상세정보_MD
	public int JOBORDER_DETAIL_MD;
	
	//작업지시서 상세정보_FD
	public int JOBORDER_DETAIL_FD;
	
	//작업지시서 상세정보_SSC Part NO.
	public String JOBORDER_DETAIL_SSCPARTNO;
	
	//작업지시서 상세정보 Rev
	public String JOBORDER_DETAIL_REV;
	
	//작업지시서 상세정보_Serial NO.
	public String JOBORDER_DETAIL_SERIALNO;
	
	//작업지시서 상세정보 HTML 코드
	public String JOBORDER_DETAIL_CODE;
	
	//작업지시서 상세정보 계획종료일
	public Date JOBORDER_DETAIL_PLANENDDAY;
	public String CONVERT_JOBORDER_DETAIL_PLANENDDAY;
	
	//작업지시서 상세정보 프레스 호기
	public Integer JOBORDER_DETAIL_PRESSNUMBER;
	
	//작업지시서 상세정보 프레스 톤
	public Integer JOBORDER_DETAIL_PRESSTON;
	
	
	public String getJOBORDER_PROCESS_SELFINSPECT_FILE_CHECK() {
		return JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK;
	}
	public void setJOBORDER_PROCESS_SELFINSPECT_FILE_CHECK(String jOBORDER_PROCESS_SELFINSPECT_FILE_CHECK) {
		JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK = jOBORDER_PROCESS_SELFINSPECT_FILE_CHECK;
	}
	public String[] getJOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2() {
		return JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2;
	}
	public void setJOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2(String[] jOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2) {
		JOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2 = jOBORDER_PROCESS_SELFINSPECT_FILE_CHECK2;
	}
	public String getPROCESS_MAIN_CATEGORY_NAME() {
		return PROCESS_MAIN_CATEGORY_NAME;
	}
	public void setPROCESS_MAIN_CATEGORY_NAME(String pROCESS_MAIN_CATEGORY_NAME) {
		PROCESS_MAIN_CATEGORY_NAME = pROCESS_MAIN_CATEGORY_NAME;
	}
	public String getEQUIPMENT_SENSOR_MATCHING_NUMBER() {
		return EQUIPMENT_SENSOR_MATCHING_NUMBER;
	}
	public void setEQUIPMENT_SENSOR_MATCHING_NUMBER(String eQUIPMENT_SENSOR_MATCHING_NUMBER) {
		EQUIPMENT_SENSOR_MATCHING_NUMBER = eQUIPMENT_SENSOR_MATCHING_NUMBER;
	}
	public String getORIGIN_EQUIPMENT_NAME() {
		return ORIGIN_EQUIPMENT_NAME;
	}
	public void setORIGIN_EQUIPMENT_NAME(String oRIGIN_EQUIPMENT_NAME) {
		ORIGIN_EQUIPMENT_NAME = oRIGIN_EQUIPMENT_NAME;
	}
	public String getORIGIN_EQUIPMENT_MODELNAME() {
		return ORIGIN_EQUIPMENT_MODELNAME;
	}
	public void setORIGIN_EQUIPMENT_MODELNAME(String oRIGIN_EQUIPMENT_MODELNAME) {
		ORIGIN_EQUIPMENT_MODELNAME = oRIGIN_EQUIPMENT_MODELNAME;
	}
	public String getORIGIN_EQUIPMENT_CONTEXT() {
		return ORIGIN_EQUIPMENT_CONTEXT;
	}
	public void setORIGIN_EQUIPMENT_CONTEXT(String oRIGIN_EQUIPMENT_CONTEXT) {
		ORIGIN_EQUIPMENT_CONTEXT = oRIGIN_EQUIPMENT_CONTEXT;
	}
	public int[] getJOBORDER_PROCESS_FILE_MANAGEMENT_ID2() {
		return JOBORDER_PROCESS_FILE_MANAGEMENT_ID2;
	}
	public void setJOBORDER_PROCESS_FILE_MANAGEMENT_ID2(int[] jOBORDER_PROCESS_FILE_MANAGEMENT_ID2) {
		JOBORDER_PROCESS_FILE_MANAGEMENT_ID2 = jOBORDER_PROCESS_FILE_MANAGEMENT_ID2;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY() {
		return SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY(String sETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY) {
		SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY = sETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;
	}
	public String getJOBORDER_PROCESS_STATUS_NAME() {
		return JOBORDER_PROCESS_STATUS_NAME;
	}
	public void setJOBORDER_PROCESS_STATUS_NAME(String jOBORDER_PROCESS_STATUS_NAME) {
		JOBORDER_PROCESS_STATUS_NAME = jOBORDER_PROCESS_STATUS_NAME;
	}
	public String getSETTING_PRESET_NAME() {
		return SETTING_PRESET_NAME;
	}
	public void setSETTING_PRESET_NAME(String sETTING_PRESET_NAME) {
		SETTING_PRESET_NAME = sETTING_PRESET_NAME;
	}
	public Date getJOBORDER_PROCESS_STOPRESULT_STOPTIME() {
		return JOBORDER_PROCESS_STOPRESULT_STOPTIME;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_STOPTIME(Date jOBORDER_PROCESS_STOPRESULT_STOPTIME) {
		JOBORDER_PROCESS_STOPRESULT_STOPTIME = jOBORDER_PROCESS_STOPRESULT_STOPTIME;
	}
	public int getPROCESS_VALUES() {
		return PROCESS_VALUES;
	}
	public void setPROCESS_VALUES(int pROCESS_VALUES) {
		PROCESS_VALUES = pROCESS_VALUES;
	}
	public int getJOBORDER_PROCESS_WORKOUT() {
		return JOBORDER_PROCESS_WORKOUT;
	}
	public void setJOBORDER_PROCESS_WORKOUT(int jOBORDER_PROCESS_WORKOUT) {
		JOBORDER_PROCESS_WORKOUT = jOBORDER_PROCESS_WORKOUT;
	}
	public int getJOBORDER_SALES() {
		return JOBORDER_SALES;
	}
	public void setJOBORDER_SALES(int jOBORDER_SALES) {
		JOBORDER_SALES = jOBORDER_SALES;
	}
	public int getJOBORDER_INDUSTRY() {
		return JOBORDER_INDUSTRY;
	}
	public void setJOBORDER_INDUSTRY(int jOBORDER_INDUSTRY) {
		JOBORDER_INDUSTRY = jOBORDER_INDUSTRY;
	}
	public String getJOBORDER_WORKINSPECTIONFILE() {
		return JOBORDER_WORKINSPECTIONFILE;
	}
	public void setJOBORDER_WORKINSPECTIONFILE(String jOBORDER_WORKINSPECTIONFILE) {
		JOBORDER_WORKINSPECTIONFILE = jOBORDER_WORKINSPECTIONFILE;
	}
	public int getTOTAL_NOT_PROCEED() {
		return TOTAL_NOT_PROCEED;
	}
	public void setTOTAL_NOT_PROCEED(int tOTAL_NOT_PROCEED) {
		TOTAL_NOT_PROCEED = tOTAL_NOT_PROCEED;
	}
	public int getMAX_VALUE() {
		return MAX_VALUE;
	}
	public void setMAX_VALUE(int mAX_VALUE) {
		MAX_VALUE = mAX_VALUE;
	}
	public String getBOM_LIST_MAIN_NAME() {
		return BOM_LIST_MAIN_NAME;
	}
	public void setBOM_LIST_MAIN_NAME(String bOM_LIST_MAIN_NAME) {
		BOM_LIST_MAIN_NAME = bOM_LIST_MAIN_NAME;
	}
	public int getBOM_LIST_QUANTITY() {
		return BOM_LIST_QUANTITY;
	}
	public void setBOM_LIST_QUANTITY(int bOM_LIST_QUANTITY) {
		BOM_LIST_QUANTITY = bOM_LIST_QUANTITY;
	}
	public int getBADQUANTITY() {
		return BADQUANTITY;
	}
	public void setBADQUANTITY(int bADQUANTITY) {
		BADQUANTITY = bADQUANTITY;
	}
	public int getOUTSOURCING() {
		return OUTSOURCING;
	}
	public void setOUTSOURCING(int oUTSOURCING) {
		OUTSOURCING = oUTSOURCING;
	}
	public int getTOTAL_PROCEED() {
		return TOTAL_PROCEED;
	}
	public void setTOTAL_PROCEED(int tOTAL_PROCEED) {
		TOTAL_PROCEED = tOTAL_PROCEED;
	}
	public int getTOTAL_JOBORDER() {
		return TOTAL_JOBORDER;
	}
	public void setTOTAL_JOBORDER(int tOTAL_JOBORDER) {
		TOTAL_JOBORDER = tOTAL_JOBORDER;
	}
	public int getTOTAL_COMPLETE() {
		return TOTAL_COMPLETE;
	}
	public void setTOTAL_COMPLETE(int tOTAL_COMPLETE) {
		TOTAL_COMPLETE = tOTAL_COMPLETE;
	}
	public String getBOM_LIST_MAIN_PRODUCTCODE() {
		return BOM_LIST_MAIN_PRODUCTCODE;
	}
	public void setBOM_LIST_MAIN_PRODUCTCODE(String bOM_LIST_MAIN_PRODUCTCODE) {
		BOM_LIST_MAIN_PRODUCTCODE = bOM_LIST_MAIN_PRODUCTCODE;
	}
	public String getBOM_DETAIL_DIVISION() {
		return BOM_DETAIL_DIVISION;
	}
	public void setBOM_DETAIL_DIVISION(String bOM_DETAIL_DIVISION) {
		BOM_DETAIL_DIVISION = bOM_DETAIL_DIVISION;
	}
	public float getBOM_DETAIL_MATERIALTHICK() {
		return BOM_DETAIL_MATERIALTHICK;
	}
	public void setBOM_DETAIL_MATERIALTHICK(float bOM_DETAIL_MATERIALTHICK) {
		BOM_DETAIL_MATERIALTHICK = bOM_DETAIL_MATERIALTHICK;
	}
	public String getBOM_DETAIL_MATERIAL() {
		return BOM_DETAIL_MATERIAL;
	}
	public void setBOM_DETAIL_MATERIAL(String bOM_DETAIL_MATERIAL) {
		BOM_DETAIL_MATERIAL = bOM_DETAIL_MATERIAL;
	}
	public float getBOM_DETAIL_C_ID() {
		return BOM_DETAIL_C_ID;
	}
	public void setBOM_DETAIL_C_ID(float bOM_DETAIL_C_ID) {
		BOM_DETAIL_C_ID = bOM_DETAIL_C_ID;
	}
	public float getBOM_DETAIL_OD() {
		return BOM_DETAIL_OD;
	}
	public void setBOM_DETAIL_OD(float bOM_DETAIL_OD) {
		BOM_DETAIL_OD = bOM_DETAIL_OD;
	}
	public int getLOG_TB_ID() {
		return LOG_TB_ID;
	}
	public void setLOG_TB_ID(int lOG_TB_ID) {
		LOG_TB_ID = lOG_TB_ID;
	}
	public int getPLAN_QUANTITY() {
		return PLAN_QUANTITY;
	}
	public void setPLAN_QUANTITY(int pLAN_QUANTITY) {
		PLAN_QUANTITY = pLAN_QUANTITY;
	}
	public int getJOBORDER_PROCESS_RESULT_RUNTIME() {
		return JOBORDER_PROCESS_RESULT_RUNTIME;
	}
	public void setJOBORDER_PROCESS_RESULT_RUNTIME(int jOBORDER_PROCESS_RESULT_RUNTIME) {
		JOBORDER_PROCESS_RESULT_RUNTIME = jOBORDER_PROCESS_RESULT_RUNTIME;
	}
	public String getJOBORDER_INSPECTIONFILE() {
		return JOBORDER_INSPECTIONFILE;
	}
	public void setJOBORDER_INSPECTIONFILE(String jOBORDER_INSPECTIONFILE) {
		JOBORDER_INSPECTIONFILE = jOBORDER_INSPECTIONFILE;
	}
	public int[] getJOBORDER_FILE_MANAGEMENT_ID2() {
		return JOBORDER_FILE_MANAGEMENT_ID2;
	}
	public void setJOBORDER_FILE_MANAGEMENT_ID2(int[] jOBORDER_FILE_MANAGEMENT_ID2) {
		JOBORDER_FILE_MANAGEMENT_ID2 = jOBORDER_FILE_MANAGEMENT_ID2;
	}
	public String[] getJOBORDER_PROCESS_REVISE_CONTEXT2() {
		return JOBORDER_PROCESS_REVISE_CONTEXT2;
	}
	public void setJOBORDER_PROCESS_REVISE_CONTEXT2(String[] jOBORDER_PROCESS_REVISE_CONTEXT2) {
		JOBORDER_PROCESS_REVISE_CONTEXT2 = jOBORDER_PROCESS_REVISE_CONTEXT2;
	}
	public String getORIGIN_PROCESS_CODE() {
		return ORIGIN_PROCESS_CODE;
	}
	public void setORIGIN_PROCESS_CODE(String oRIGIN_PROCESS_CODE) {
		ORIGIN_PROCESS_CODE = oRIGIN_PROCESS_CODE;
	}
	public String[] getJOBORDER_UNIQUESS_CONTEXT2() {
		return JOBORDER_UNIQUESS_CONTEXT2;
	}
	public void setJOBORDER_UNIQUESS_CONTEXT2(String[] jOBORDER_UNIQUESS_CONTEXT2) {
		JOBORDER_UNIQUESS_CONTEXT2 = jOBORDER_UNIQUESS_CONTEXT2;
	}
	public int[] getJOBORDER_UNIQUESS_ID2() {
		return JOBORDER_UNIQUESS_ID2;
	}
	public void setJOBORDER_UNIQUESS_ID2(int[] jOBORDER_UNIQUESS_ID2) {
		JOBORDER_UNIQUESS_ID2 = jOBORDER_UNIQUESS_ID2;
	}
	public int[] getJOBORDER_PROCESS_ID2() {
		return JOBORDER_PROCESS_ID2;
	}
	public void setJOBORDER_PROCESS_ID2(int[] jOBORDER_PROCESS_ID2) {
		JOBORDER_PROCESS_ID2 = jOBORDER_PROCESS_ID2;
	}
	public String getORIGIN_ACCOUNT_MEMBERNAME() {
		return ORIGIN_ACCOUNT_MEMBERNAME;
	}
	public void setORIGIN_ACCOUNT_MEMBERNAME(String oRIGIN_ACCOUNT_MEMBERNAME) {
		ORIGIN_ACCOUNT_MEMBERNAME = oRIGIN_ACCOUNT_MEMBERNAME;
	}
	public String getJOBORDER_CODEFILE() {
		return JOBORDER_CODEFILE;
	}
	public void setJOBORDER_CODEFILE(String jOBORDER_CODEFILE) {
		JOBORDER_CODEFILE = jOBORDER_CODEFILE;
	}
	public int[] getSETTING_PRESET_FILE_MANAGEMENT_ID2() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID2(int[] sETTING_PRESET_FILE_MANAGEMENT_ID2) {
		SETTING_PRESET_FILE_MANAGEMENT_ID2 = sETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public int getSETTING_PRESET_FILE_MANAGEMENT_ID() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID(int sETTING_PRESET_FILE_MANAGEMENT_ID) {
		SETTING_PRESET_FILE_MANAGEMENT_ID = sETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public Integer getSETTING_PRESET_ID() {
		return SETTING_PRESET_ID;
	}
	public void setSETTING_PRESET_ID(Integer sETTING_PRESET_ID) {
		SETTING_PRESET_ID = sETTING_PRESET_ID;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_NAME() {
		return SETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_NAME(String sETTING_PRESET_FILE_MANAGEMENT_NAME) {
		SETTING_PRESET_FILE_MANAGEMENT_NAME = sETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY() {
		return SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY(String sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY) {
		SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY = sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public int getJOBORDER_LOBBY_ACTIVITY_ID1() {
		return JOBORDER_LOBBY_ACTIVITY_ID1;
	}
	public void setJOBORDER_LOBBY_ACTIVITY_ID1(int jOBORDER_LOBBY_ACTIVITY_ID1) {
		JOBORDER_LOBBY_ACTIVITY_ID1 = jOBORDER_LOBBY_ACTIVITY_ID1;
	}
	public int getJOBORDER_LOBBY_ACTIVITY_ID2() {
		return JOBORDER_LOBBY_ACTIVITY_ID2;
	}
	public void setJOBORDER_LOBBY_ACTIVITY_ID2(int jOBORDER_LOBBY_ACTIVITY_ID2) {
		JOBORDER_LOBBY_ACTIVITY_ID2 = jOBORDER_LOBBY_ACTIVITY_ID2;
	}
	public int getJOBORDER_LOBBY_ACTIVITY_ID3() {
		return JOBORDER_LOBBY_ACTIVITY_ID3;
	}
	public void setJOBORDER_LOBBY_ACTIVITY_ID3(int jOBORDER_LOBBY_ACTIVITY_ID3) {
		JOBORDER_LOBBY_ACTIVITY_ID3 = jOBORDER_LOBBY_ACTIVITY_ID3;
	}
	public String[][] getJOBORDER_UNIQUESS_CONTEXT3() {
		return JOBORDER_UNIQUESS_CONTEXT3;
	}
	public void setJOBORDER_UNIQUESS_CONTEXT3(String[][] jOBORDER_UNIQUESS_CONTEXT3) {
		JOBORDER_UNIQUESS_CONTEXT3 = jOBORDER_UNIQUESS_CONTEXT3;
	}
	public int[] getJOBORDER_PROCESS_INDEX2() {
		return JOBORDER_PROCESS_INDEX2;
	}
	public void setJOBORDER_PROCESS_INDEX2(int[] jOBORDER_PROCESS_INDEX2) {
		JOBORDER_PROCESS_INDEX2 = jOBORDER_PROCESS_INDEX2;
	}
	public float[] getJOBORDER_PROCESS_WORKTIME2() {
		return JOBORDER_PROCESS_WORKTIME2;
	}
	public void setJOBORDER_PROCESS_WORKTIME2(float[] jOBORDER_PROCESS_WORKTIME2) {
		JOBORDER_PROCESS_WORKTIME2 = jOBORDER_PROCESS_WORKTIME2;
	}
	public String[] getJOBORDER_PROCESS_SELFINSPECT_FILE2() {
		return JOBORDER_PROCESS_SELFINSPECT_FILE2;
	}
	public void setJOBORDER_PROCESS_SELFINSPECT_FILE2(String[] jOBORDER_PROCESS_SELFINSPECT_FILE2) {
		JOBORDER_PROCESS_SELFINSPECT_FILE2 = jOBORDER_PROCESS_SELFINSPECT_FILE2;
	}

	public int[] getORIGIN_PROCESS_ID2() {
		return ORIGIN_PROCESS_ID2;
	}
	public void setORIGIN_PROCESS_ID2(int[] oRIGIN_PROCESS_ID2) {
		ORIGIN_PROCESS_ID2 = oRIGIN_PROCESS_ID2;
	}
	public int[] getJOBORDER_FILE_TYPE_ID2() {
		return JOBORDER_FILE_TYPE_ID2;
	}
	public void setJOBORDER_FILE_TYPE_ID2(int[] jOBORDER_FILE_TYPE_ID2) {
		JOBORDER_FILE_TYPE_ID2 = jOBORDER_FILE_TYPE_ID2;
	}
	public String getDEL_firstday() {
		return DEL_firstday;
	}
	public void setDEL_firstday(String dEL_firstday) {
		DEL_firstday = dEL_firstday;
	}
	public String getDEL_secondday() {
		return DEL_secondday;
	}
	public void setDEL_secondday(String dEL_secondday) {
		DEL_secondday = dEL_secondday;
	}
	public String getPUB_firsday() {
		return PUB_firsday;
	}
	public void setPUB_firsday(String pUB_firsday) {
		PUB_firsday = pUB_firsday;
	}
	public String getPUB_secondday() {
		return PUB_secondday;
	}
	public void setPUB_secondday(String pUB_secondday) {
		PUB_secondday = pUB_secondday;
	}
	public String getBOM_DETAIL_PRODUCTCODE() {
		return BOM_DETAIL_PRODUCTCODE;
	}
	public void setBOM_DETAIL_PRODUCTCODE(String bOM_DETAIL_PRODUCTCODE) {
		BOM_DETAIL_PRODUCTCODE = bOM_DETAIL_PRODUCTCODE;
	}
	public String getBOM_DETAIL_BELLOWSCODE() {
		return BOM_DETAIL_BELLOWSCODE;
	}
	public void setBOM_DETAIL_BELLOWSCODE(String bOM_DETAIL_BELLOWSCODE) {
		BOM_DETAIL_BELLOWSCODE = bOM_DETAIL_BELLOWSCODE;
	}
	public String getJOBORDER_EMERGENCY_STATUS_NAME() {
		return JOBORDER_EMERGENCY_STATUS_NAME;
	}
	public void setJOBORDER_EMERGENCY_STATUS_NAME(String jOBORDER_EMERGENCY_STATUS_NAME) {
		JOBORDER_EMERGENCY_STATUS_NAME = jOBORDER_EMERGENCY_STATUS_NAME;
	}
	public int getCT_FILE_REGISTER_DRAWING() {
		return CT_FILE_REGISTER_DRAWING;
	}
	public void setCT_FILE_REGISTER_DRAWING(int cT_FILE_REGISTER_DRAWING) {
		CT_FILE_REGISTER_DRAWING = cT_FILE_REGISTER_DRAWING;
	}
	public String getJOBORDER_STATUS_NAME() {
		return JOBORDER_STATUS_NAME;
	}
	public void setJOBORDER_STATUS_NAME(String jOBORDER_STATUS_NAME) {
		JOBORDER_STATUS_NAME = jOBORDER_STATUS_NAME;
	}
	public int getJOBORDER_PROCESS_FILE_MANAGEMENT_ID() {
		return JOBORDER_PROCESS_FILE_MANAGEMENT_ID;
	}
	public void setJOBORDER_PROCESS_FILE_MANAGEMENT_ID(int jOBORDER_PROCESS_FILE_MANAGEMENT_ID) {
		JOBORDER_PROCESS_FILE_MANAGEMENT_ID = jOBORDER_PROCESS_FILE_MANAGEMENT_ID;
	}
	public String getJOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME() {
		return JOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME;
	}
	public void setJOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME(String jOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME) {
		JOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME = jOBORDER_PROCESS_FILE_MANAGEMENT_FILENAME;
	}
	public String getJOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY() {
		return JOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY;
	}
	public void setJOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY(String jOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY) {
		JOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY = jOBORDER_PROCESS_FILE_MANAGEMENT_FILEDIRECTORY;
	}
	public int getJOBORDER_PROCESS_STATUS_ID1() {
		return JOBORDER_PROCESS_STATUS_ID1;
	}
	public void setJOBORDER_PROCESS_STATUS_ID1(int jOBORDER_PROCESS_STATUS_ID1) {
		JOBORDER_PROCESS_STATUS_ID1 = jOBORDER_PROCESS_STATUS_ID1;
	}
	public int getJOBORDER_PROCESS_STATUS_ID2() {
		return JOBORDER_PROCESS_STATUS_ID2;
	}
	public void setJOBORDER_PROCESS_STATUS_ID2(int jOBORDER_PROCESS_STATUS_ID2) {
		JOBORDER_PROCESS_STATUS_ID2 = jOBORDER_PROCESS_STATUS_ID2;
	}
	public Date getJOBORDER_PROCESS_RESULT_STARTTIME() {
		return JOBORDER_PROCESS_RESULT_STARTTIME;
	}
	public void setJOBORDER_PROCESS_RESULT_STARTTIME(Date jOBORDER_PROCESS_RESULT_STARTTIME) {
		JOBORDER_PROCESS_RESULT_STARTTIME = jOBORDER_PROCESS_RESULT_STARTTIME;
	}
	public Date getJOBORDER_PROCESS_RESULT_ENDTIME() {
		return JOBORDER_PROCESS_RESULT_ENDTIME;
	}
	public void setJOBORDER_PROCESS_RESULT_ENDTIME(Date jOBORDER_PROCESS_RESULT_ENDTIME) {
		JOBORDER_PROCESS_RESULT_ENDTIME = jOBORDER_PROCESS_RESULT_ENDTIME;
	}
	public int getPROCESS_RESULT_TEMPLATE_ID() {
		return PROCESS_RESULT_TEMPLATE_ID;
	}
	public void setPROCESS_RESULT_TEMPLATE_ID(int pROCESS_RESULT_TEMPLATE_ID) {
		PROCESS_RESULT_TEMPLATE_ID = pROCESS_RESULT_TEMPLATE_ID;
	}
	public String getPROCESS_RESULT_TEMPLATE_QUANTITY() {
		return PROCESS_RESULT_TEMPLATE_QUANTITY;
	}
	public void setPROCESS_RESULT_TEMPLATE_QUANTITY(String pROCESS_RESULT_TEMPLATE_QUANTITY) {
		PROCESS_RESULT_TEMPLATE_QUANTITY = pROCESS_RESULT_TEMPLATE_QUANTITY;
	}
	public String getPROCESS_RESULT_TEMPLATE_BADQUANTITY() {
		return PROCESS_RESULT_TEMPLATE_BADQUANTITY;
	}
	public void setPROCESS_RESULT_TEMPLATE_BADQUANTITY(String pROCESS_RESULT_TEMPLATE_BADQUANTITY) {
		PROCESS_RESULT_TEMPLATE_BADQUANTITY = pROCESS_RESULT_TEMPLATE_BADQUANTITY;
	}
	public String getPROCESS_RESULT_TEMPLATE_GOODQUANTITY() {
		return PROCESS_RESULT_TEMPLATE_GOODQUANTITY;
	}
	public void setPROCESS_RESULT_TEMPLATE_GOODQUANTITY(String pROCESS_RESULT_TEMPLATE_GOODQUANTITY) {
		PROCESS_RESULT_TEMPLATE_GOODQUANTITY = pROCESS_RESULT_TEMPLATE_GOODQUANTITY;
	}
	public float getJOBORDER_PROCESS_RUNNIGTIME() {
		return JOBORDER_PROCESS_RUNNIGTIME;
	}
	public void setJOBORDER_PROCESS_RUNNIGTIME(float jOBORDER_PROCESS_RUNNIGTIME) {
		JOBORDER_PROCESS_RUNNIGTIME = jOBORDER_PROCESS_RUNNIGTIME;
	}
	public String getPROCESS_RESULT_TEMPLATE_BADCODE() {
		return PROCESS_RESULT_TEMPLATE_BADCODE;
	}
	public void setPROCESS_RESULT_TEMPLATE_BADCODE(String pROCESS_RESULT_TEMPLATE_BADCODE) {
		PROCESS_RESULT_TEMPLATE_BADCODE = pROCESS_RESULT_TEMPLATE_BADCODE;
	}

	public int getJOBORDER_PROCESS_REVISE_ID() {
		return JOBORDER_PROCESS_REVISE_ID;
	}
	public void setJOBORDER_PROCESS_REVISE_ID(int jOBORDER_PROCESS_REVISE_ID) {
		JOBORDER_PROCESS_REVISE_ID = jOBORDER_PROCESS_REVISE_ID;
	}
	public String getJOBORDER_PROCESS_REVISE_CONTEXT() {
		return JOBORDER_PROCESS_REVISE_CONTEXT;
	}
	public void setJOBORDER_PROCESS_REVISE_CONTEXT(String jOBORDER_PROCESS_REVISE_CONTEXT) {
		JOBORDER_PROCESS_REVISE_CONTEXT = jOBORDER_PROCESS_REVISE_CONTEXT;
	}
	public Date getJOBORDER_PROCESS_REVISE_TIME() {
		return JOBORDER_PROCESS_REVISE_TIME;
	}
	public void setJOBORDER_PROCESS_REVISE_TIME(Date jOBORDER_PROCESS_REVISE_TIME) {
		JOBORDER_PROCESS_REVISE_TIME = jOBORDER_PROCESS_REVISE_TIME;
	}
	public int getJOBORDER_PROCESS_STOPRESULT_ID() {
		return JOBORDER_PROCESS_STOPRESULT_ID;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_ID(int jOBORDER_PROCESS_STOPRESULT_ID) {
		JOBORDER_PROCESS_STOPRESULT_ID = jOBORDER_PROCESS_STOPRESULT_ID;
	}
	public Date getJOBORDER_PROCESS_STOPRESULT_RESTARTTIME() {
		return JOBORDER_PROCESS_STOPRESULT_RESTARTTIME;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_RESTARTTIME(Date jOBORDER_PROCESS_STOPRESULT_RESTARTTIME) {
		JOBORDER_PROCESS_STOPRESULT_RESTARTTIME = jOBORDER_PROCESS_STOPRESULT_RESTARTTIME;
	}
	public String getJOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME() {
		return JOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME(String jOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME) {
		JOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME = jOBORDER_PROCESS_STOPRESULT_ACCOUNT_NAME;
	}
	public String getJOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER() {
		return JOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER(
			String jOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER) {
		JOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER = jOBORDER_PROCESS_STOPRESULT_ACCOUNT_EMPLOYMENTNUMBER;
	}
	public String getJOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT() {
		return JOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT;
	}
	public void setJOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT(String jOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT) {
		JOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT = jOBORDER_PROCESS_STOPRESULT_STOP_CONTEXT;
	}
	public int getJOBORDER_EQUIPMENT_ID() {
		return JOBORDER_EQUIPMENT_ID;
	}
	public void setJOBORDER_EQUIPMENT_ID(int jOBORDER_EQUIPMENT_ID) {
		JOBORDER_EQUIPMENT_ID = jOBORDER_EQUIPMENT_ID;
	}
	public String getJOBORDER_EQUIPMENTNAME() {
		return JOBORDER_EQUIPMENTNAME;
	}
	public void setJOBORDER_EQUIPMENTNAME(String jOBORDER_EQUIPMENTNAME) {
		JOBORDER_EQUIPMENTNAME = jOBORDER_EQUIPMENTNAME;
	}
	public String getJOBORDER_EQUIPMENTMODELNAME() {
		return JOBORDER_EQUIPMENTMODELNAME;
	}
	public void setJOBORDER_EQUIPMENTMODELNAME(String jOBORDER_EQUIPMENTMODELNAME) {
		JOBORDER_EQUIPMENTMODELNAME = jOBORDER_EQUIPMENTMODELNAME;
	}
	public String getJOBORDER_EQUIPMENTCONTEXT() {
		return JOBORDER_EQUIPMENTCONTEXT;
	}
	public void setJOBORDER_EQUIPMENTCONTEXT(String jOBORDER_EQUIPMENTCONTEXT) {
		JOBORDER_EQUIPMENTCONTEXT = jOBORDER_EQUIPMENTCONTEXT;
	}
	public int getJOBORDER_EQUIPMENTUSEON() {
		return JOBORDER_EQUIPMENTUSEON;
	}
	public void setJOBORDER_EQUIPMENTUSEON(int jOBORDER_EQUIPMENTUSEON) {
		JOBORDER_EQUIPMENTUSEON = jOBORDER_EQUIPMENTUSEON;
	}
	public int getJOBORDER_UNIQUESS_ID() {
		return JOBORDER_UNIQUESS_ID;
	}
	public void setJOBORDER_UNIQUESS_ID(int jOBORDER_UNIQUESS_ID) {
		JOBORDER_UNIQUESS_ID = jOBORDER_UNIQUESS_ID;
	}
	public String getJOBORDER_UNIQUESS_CONTEXT() {
		return JOBORDER_UNIQUESS_CONTEXT;
	}
	public void setJOBORDER_UNIQUESS_CONTEXT(String jOBORDER_UNIQUESS_CONTEXT) {
		JOBORDER_UNIQUESS_CONTEXT = jOBORDER_UNIQUESS_CONTEXT;
	}
	public int getORIGIN_PROCESS_OUTSOURCING_REGISTER() {
		return ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public void setORIGIN_PROCESS_OUTSOURCING_REGISTER(int oRIGIN_PROCESS_OUTSOURCING_REGISTER) {
		ORIGIN_PROCESS_OUTSOURCING_REGISTER = oRIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NAME() {
		return ORIGIN_PROCESS_CUSTOMER_NAME;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NAME(String oRIGIN_PROCESS_CUSTOMER_NAME) {
		ORIGIN_PROCESS_CUSTOMER_NAME = oRIGIN_PROCESS_CUSTOMER_NAME;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NUMBER() {
		return ORIGIN_PROCESS_CUSTOMER_NUMBER;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NUMBER(String oRIGIN_PROCESS_CUSTOMER_NUMBER) {
		ORIGIN_PROCESS_CUSTOMER_NUMBER = oRIGIN_PROCESS_CUSTOMER_NUMBER;
	}
	public String getORIGIN_PROCESS_NAME() {
		return ORIGIN_PROCESS_NAME;
	}
	public void setORIGIN_PROCESS_NAME(String oRIGIN_PROCESS_NAME) {
		ORIGIN_PROCESS_NAME = oRIGIN_PROCESS_NAME;
	}
	public int getORIGIN_PROCESS_ID() {
		return ORIGIN_PROCESS_ID;
	}
	public void setORIGIN_PROCESS_ID(int oRIGIN_PROCESS_ID) {
		ORIGIN_PROCESS_ID = oRIGIN_PROCESS_ID;
	}
	public int getJOBORDER_PROCESS_ID() {
		return JOBORDER_PROCESS_ID;
	}
	public void setJOBORDER_PROCESS_ID(int jOBORDER_PROCESS_ID) {
		JOBORDER_PROCESS_ID = jOBORDER_PROCESS_ID;
	}
	public int getPROCESS_MAIN_CATEGORY_ID() {
		return PROCESS_MAIN_CATEGORY_ID;
	}
	public void setPROCESS_MAIN_CATEGORY_ID(int pROCESS_MAIN_CATEGORY_ID) {
		PROCESS_MAIN_CATEGORY_ID = pROCESS_MAIN_CATEGORY_ID;
	}
	public int getJOBORDER_FORM_DETAIL_ID() {
		return JOBORDER_FORM_DETAIL_ID;
	}
	public void setJOBORDER_FORM_DETAIL_ID(int jOBORDER_FORM_DETAIL_ID) {
		JOBORDER_FORM_DETAIL_ID = jOBORDER_FORM_DETAIL_ID;
	}
	public int getJOBORDER_PROCESS_RESULT_ID() {
		return JOBORDER_PROCESS_RESULT_ID;
	}
	public void setJOBORDER_PROCESS_RESULT_ID(int jOBORDER_PROCESS_RESULT_ID) {
		JOBORDER_PROCESS_RESULT_ID = jOBORDER_PROCESS_RESULT_ID;
	}
	public int getJOBORDER_PROCESS_STATUS_ID() {
		return JOBORDER_PROCESS_STATUS_ID;
	}
	public void setJOBORDER_PROCESS_STATUS_ID(int jOBORDER_PROCESS_STATUS_ID) {
		JOBORDER_PROCESS_STATUS_ID = jOBORDER_PROCESS_STATUS_ID;
	}
	public String getJOBORDER_PROCESS_NAME() {
		return JOBORDER_PROCESS_NAME;
	}
	public void setJOBORDER_PROCESS_NAME(String jOBORDER_PROCESS_NAME) {
		JOBORDER_PROCESS_NAME = jOBORDER_PROCESS_NAME;
	}
	public int getJOBORDER_PROCESS_INDEX() {
		return JOBORDER_PROCESS_INDEX;
	}
	public void setJOBORDER_PROCESS_INDEX(int jOBORDER_PROCESS_INDEX) {
		JOBORDER_PROCESS_INDEX = jOBORDER_PROCESS_INDEX;
	}
	public int getJOBORDER_PROCESS_FOCUSON() {
		return JOBORDER_PROCESS_FOCUSON;
	}
	public void setJOBORDER_PROCESS_FOCUSON(int jOBORDER_PROCESS_FOCUSON) {
		JOBORDER_PROCESS_FOCUSON = jOBORDER_PROCESS_FOCUSON;
	}
	public float getJOBORDER_PROCESS_WORKTIME() {
		return JOBORDER_PROCESS_WORKTIME;
	}
	public void setJOBORDER_PROCESS_WORKTIME(float jOBORDER_PROCESS_WORKTIME) {
		JOBORDER_PROCESS_WORKTIME = jOBORDER_PROCESS_WORKTIME;
	}
	public String getJOBORDER_PROCESS_SELFINSPECT_FILE() {
		return JOBORDER_PROCESS_SELFINSPECT_FILE;
	}
	public void setJOBORDER_PROCESS_SELFINSPECT_FILE(String jOBORDER_PROCESS_SELFINSPECT_FILE) {
		JOBORDER_PROCESS_SELFINSPECT_FILE = jOBORDER_PROCESS_SELFINSPECT_FILE;
	}
	public String getJOBORDER_PRCOESS_FILE() {
		return JOBORDER_PRCOESS_FILE;
	}
	public void setJOBORDER_PRCOESS_FILE(String jOBORDER_PRCOESS_FILE) {
		JOBORDER_PRCOESS_FILE = jOBORDER_PRCOESS_FILE;
	}
	public Date getJOBORDER_PROCESS_STARTDAY() {
		return JOBORDER_PROCESS_STARTDAY;
	}
	public void setJOBORDER_PROCESS_STARTDAY(Date jOBORDER_PROCESS_STARTDAY) {
		JOBORDER_PROCESS_STARTDAY = jOBORDER_PROCESS_STARTDAY;
	}
	public Date getJOBORDER_PROCESS_ENDDAY() {
		return JOBORDER_PROCESS_ENDDAY;
	}
	public void setJOBORDER_PROCESS_ENDDAY(Date jOBORDER_PROCESS_ENDDAY) {
		JOBORDER_PROCESS_ENDDAY = jOBORDER_PROCESS_ENDDAY;
	}
	public int getJOBORDER_PROCESS_OUTSOURCING() {
		return JOBORDER_PROCESS_OUTSOURCING;
	}
	public void setJOBORDER_PROCESS_OUTSOURCING(int jOBORDER_PROCESS_OUTSOURCING) {
		JOBORDER_PROCESS_OUTSOURCING = jOBORDER_PROCESS_OUTSOURCING;
	}
	public String getJOBORDER_PROCESS_CUSTOMERNAME() {
		return JOBORDER_PROCESS_CUSTOMERNAME;
	}
	public void setJOBORDER_PROCESS_CUSTOMERNAME(String jOBORDER_PROCESS_CUSTOMERNAME) {
		JOBORDER_PROCESS_CUSTOMERNAME = jOBORDER_PROCESS_CUSTOMERNAME;
	}
	public String getJOBORDER_PROCESS_CUSTOMERNUMBER() {
		return JOBORDER_PROCESS_CUSTOMERNUMBER;
	}
	public void setJOBORDER_PROCESS_CUSTOMERNUMBER(String jOBORDER_PROCESS_CUSTOMERNUMBER) {
		JOBORDER_PROCESS_CUSTOMERNUMBER = jOBORDER_PROCESS_CUSTOMERNUMBER;
	}
	public int getQRCODE_ID() {
		return QRCODE_ID;
	}
	public void setQRCODE_ID(int qRCODE_ID) {
		QRCODE_ID = qRCODE_ID;
	}
	public String getQRCODE_DIRECTORY() {
		return QRCODE_DIRECTORY;
	}
	public void setQRCODE_DIRECTORY(String qRCODE_DIRECTORY) {
		QRCODE_DIRECTORY = qRCODE_DIRECTORY;
	}
	public Date getJOBORDER_DETAIL_PLANENDDAY() {
		return JOBORDER_DETAIL_PLANENDDAY;
	}
	public void setJOBORDER_DETAIL_PLANENDDAY(Date jOBORDER_DETAIL_PLANENDDAY) {
		JOBORDER_DETAIL_PLANENDDAY = jOBORDER_DETAIL_PLANENDDAY;
	}
	public String getCONVERT_JOBORDER_DETAIL_PLANENDDAY() {
		return CONVERT_JOBORDER_DETAIL_PLANENDDAY;
	}
	public void setCONVERT_JOBORDER_DETAIL_PLANENDDAY(String cONVERT_JOBORDER_DETAIL_PLANENDDAY) {
		CONVERT_JOBORDER_DETAIL_PLANENDDAY = cONVERT_JOBORDER_DETAIL_PLANENDDAY;
	}
	public Integer getJOBORDER_DETAIL_PRESSNUMBER() {
		return JOBORDER_DETAIL_PRESSNUMBER;
	}
	public void setJOBORDER_DETAIL_PRESSNUMBER(Integer jOBORDER_DETAIL_PRESSNUMBER) {
		JOBORDER_DETAIL_PRESSNUMBER = jOBORDER_DETAIL_PRESSNUMBER;
	}
	public Integer getJOBORDER_DETAIL_PRESSTON() {
		return JOBORDER_DETAIL_PRESSTON;
	}
	public void setJOBORDER_DETAIL_PRESSTON(Integer jOBORDER_DETAIL_PRESSTON) {
		JOBORDER_DETAIL_PRESSTON = jOBORDER_DETAIL_PRESSTON;
	}
	public int getJOBORDER_FILE_MANAGEMENT_ID() {
		return JOBORDER_FILE_MANAGEMENT_ID;
	}
	public void setJOBORDER_FILE_MANAGEMENT_ID(int jOBORDER_FILE_MANAGEMENT_ID) {
		JOBORDER_FILE_MANAGEMENT_ID = jOBORDER_FILE_MANAGEMENT_ID;
	}
	public int getJOBORDER_FILE_TYPE_ID() {
		return JOBORDER_FILE_TYPE_ID;
	}
	public void setJOBORDER_FILE_TYPE_ID(int jOBORDER_FILE_TYPE_ID) {
		JOBORDER_FILE_TYPE_ID = jOBORDER_FILE_TYPE_ID;
	}
	public String getJOBORDER_FILE_MANAGEMENT_NAME() {
		return JOBORDER_FILE_MANAGEMENT_NAME;
	}
	public void setJOBORDER_FILE_MANAGEMENT_NAME(String jOBORDER_FILE_MANAGEMENT_NAME) {
		JOBORDER_FILE_MANAGEMENT_NAME = jOBORDER_FILE_MANAGEMENT_NAME;
	}
	public String getJOBORDER_FILE_MANAGEMENT_DIRECTORY() {
		return JOBORDER_FILE_MANAGEMENT_DIRECTORY;
	}
	public void setJOBORDER_FILE_MANAGEMENT_DIRECTORY(String jOBORDER_FILE_MANAGEMENT_DIRECTORY) {
		JOBORDER_FILE_MANAGEMENT_DIRECTORY = jOBORDER_FILE_MANAGEMENT_DIRECTORY;
	}
	public int getJOBORDER_ID() {
		return JOBORDER_ID;
	}
	public void setJOBORDER_ID(int jOBORDER_ID) {
		JOBORDER_ID = jOBORDER_ID;
	}
	public int getJOBORDER_LOBBY_ACTIVITY_ID() {
		return JOBORDER_LOBBY_ACTIVITY_ID;
	}
	public void setJOBORDER_LOBBY_ACTIVITY_ID(int jOBORDER_LOBBY_ACTIVITY_ID) {
		JOBORDER_LOBBY_ACTIVITY_ID = jOBORDER_LOBBY_ACTIVITY_ID;
	}
	public int getJOBORDER_EMERGENCY_ID() {
		return JOBORDER_EMERGENCY_ID;
	}
	public void setJOBORDER_EMERGENCY_ID(int jOBORDER_EMERGENCY_ID) {
		JOBORDER_EMERGENCY_ID = jOBORDER_EMERGENCY_ID;
	}
	public int getCT_FILE_REGISTER_ID() {
		return CT_FILE_REGISTER_ID;
	}
	public void setCT_FILE_REGISTER_ID(int cT_FILE_REGISTER_ID) {
		CT_FILE_REGISTER_ID = cT_FILE_REGISTER_ID;
	}
	public int getJOBORDER_STATUS_ID() {
		return JOBORDER_STATUS_ID;
	}
	public void setJOBORDER_STATUS_ID(int jOBORDER_STATUS_ID) {
		JOBORDER_STATUS_ID = jOBORDER_STATUS_ID;
	}
	public int getORIGIN_ACCOUNT_ID() {
		return ORIGIN_ACCOUNT_ID;
	}
	public void setORIGIN_ACCOUNT_ID(int oRIGIN_ACCOUNT_ID) {
		ORIGIN_ACCOUNT_ID = oRIGIN_ACCOUNT_ID;
	}
	public int getBOM_DETAIL_ID() {
		return BOM_DETAIL_ID;
	}
	public void setBOM_DETAIL_ID(int bOM_DETAIL_ID) {
		BOM_DETAIL_ID = bOM_DETAIL_ID;
	}
	public int getBOM_LIST_ID() {
		return BOM_LIST_ID;
	}
	public void setBOM_LIST_ID(int bOM_LIST_ID) {
		BOM_LIST_ID = bOM_LIST_ID;
	}
	public Integer getJOBORDER_PUBLISH() {
		return JOBORDER_PUBLISH;
	}
	public void setJOBORDER_PUBLISH(Integer jOBORDER_PUBLISH) {
		JOBORDER_PUBLISH = jOBORDER_PUBLISH;
	}
	public Date getJOBORDER_PUBLISHDAY() {
		return JOBORDER_PUBLISHDAY;
	}
	public void setJOBORDER_PUBLISHDAY(Date jOBORDER_PUBLISHDAY) {
		JOBORDER_PUBLISHDAY = jOBORDER_PUBLISHDAY;
	}
	public Date getJOBORDER_STARTDAY() {
		return JOBORDER_STARTDAY;
	}
	public void setJOBORDER_STARTDAY(Date jOBORDER_STARTDAY) {
		JOBORDER_STARTDAY = jOBORDER_STARTDAY;
	}
	public Date getJOBORDER_ENDDAY() {
		return JOBORDER_ENDDAY;
	}
	public void setJOBORDER_ENDDAY(Date jOBORDER_ENDDAY) {
		JOBORDER_ENDDAY = jOBORDER_ENDDAY;
	}
	public String getJOBORDER_CONTEXT() {
		return JOBORDER_CONTEXT;
	}
	public void setJOBORDER_CONTEXT(String jOBORDER_CONTEXT) {
		JOBORDER_CONTEXT = jOBORDER_CONTEXT;
	}
	public String getJOBORDER_DETAIL_CODE() {
		return JOBORDER_DETAIL_CODE;
	}
	public void setJOBORDER_DETAIL_CODE(String jOBORDER_DETAIL_CODE) {
		JOBORDER_DETAIL_CODE = jOBORDER_DETAIL_CODE;
	}
	public Date getJOBORDER_DETAIL_DEILVERYDAY() {
		return JOBORDER_DETAIL_DEILVERYDAY;
	}
	public void setJOBORDER_DETAIL_DEILVERYDAY(Date jOBORDER_DETAIL_DEILVERYDAY) {
		JOBORDER_DETAIL_DEILVERYDAY = jOBORDER_DETAIL_DEILVERYDAY;
	}
	public String getCONVERT_JOBORDER_DETAIL_DEILVERYDAY() {
		return CONVERT_JOBORDER_DETAIL_DEILVERYDAY;
	}
	public void setCONVERT_JOBORDER_DETAIL_DEILVERYDAY(String cONVERT_JOBORDER_DETAIL_DEILVERYDAY) {
		CONVERT_JOBORDER_DETAIL_DEILVERYDAY = cONVERT_JOBORDER_DETAIL_DEILVERYDAY;
	}
	public int getJOBORDER_DETAIL_ID() {
		return JOBORDER_DETAIL_ID;
	}
	public void setJOBORDER_DETAIL_ID(int jOBORDER_DETAIL_ID) {
		JOBORDER_DETAIL_ID = jOBORDER_DETAIL_ID;
	}
	public String getJOBORDER_DETAIL_BUSINESSNAME() {
		return JOBORDER_DETAIL_BUSINESSNAME;
	}
	public void setJOBORDER_DETAIL_BUSINESSNAME(String jOBORDER_DETAIL_BUSINESSNAME) {
		JOBORDER_DETAIL_BUSINESSNAME = jOBORDER_DETAIL_BUSINESSNAME;
	}
	public String getJOBORDER_DETAIL_PRODUCTNAME() {
		return JOBORDER_DETAIL_PRODUCTNAME;
	}
	public void setJOBORDER_DETAIL_PRODUCTNAME(String jOBORDER_DETAIL_PRODUCTNAME) {
		JOBORDER_DETAIL_PRODUCTNAME = jOBORDER_DETAIL_PRODUCTNAME;
	}
	public int getJOBORDER_DETAIL_QUANTITY() {
		return JOBORDER_DETAIL_QUANTITY;
	}
	public void setJOBORDER_DETAIL_QUANTITY(int jOBORDER_DETAIL_QUANTITY) {
		JOBORDER_DETAIL_QUANTITY = jOBORDER_DETAIL_QUANTITY;
	}
	public String getJOBORDER_DETAIL_CLIENT() {
		return JOBORDER_DETAIL_CLIENT;
	}
	public void setJOBORDER_DETAIL_CLIENT(String jOBORDER_DETAIL_CLIENT) {
		JOBORDER_DETAIL_CLIENT = jOBORDER_DETAIL_CLIENT;
	}
	public String getJOBORDER_DETAIL_JOBNUMBER() {
		return JOBORDER_DETAIL_JOBNUMBER;
	}
	public void setJOBORDER_DETAIL_JOBNUMBER(String jOBORDER_DETAIL_JOBNUMBER) {
		JOBORDER_DETAIL_JOBNUMBER = jOBORDER_DETAIL_JOBNUMBER;
	}
	public String getJOBORDER_DETAIL_PRODUCTNUMBER() {
		return JOBORDER_DETAIL_PRODUCTNUMBER;
	}
	public void setJOBORDER_DETAIL_PRODUCTNUMBER(String jOBORDER_DETAIL_PRODUCTNUMBER) {
		JOBORDER_DETAIL_PRODUCTNUMBER = jOBORDER_DETAIL_PRODUCTNUMBER;
	}
	public int getJOBORDER_DETAIL_SIZE() {
		return JOBORDER_DETAIL_SIZE;
	}
	public void setJOBORDER_DETAIL_SIZE(int jOBORDER_DETAIL_SIZE) {
		JOBORDER_DETAIL_SIZE = jOBORDER_DETAIL_SIZE;
	}
	public float getJOBORDER_DETAIL_SHEARINGWIDTH() {
		return JOBORDER_DETAIL_SHEARINGWIDTH;
	}
	public void setJOBORDER_DETAIL_SHEARINGWIDTH(float jOBORDER_DETAIL_SHEARINGWIDTH) {
		JOBORDER_DETAIL_SHEARINGWIDTH = jOBORDER_DETAIL_SHEARINGWIDTH;
	}
	public int getJOBORDER_DETAIL_MD() {
		return JOBORDER_DETAIL_MD;
	}
	public void setJOBORDER_DETAIL_MD(int jOBORDER_DETAIL_MD) {
		JOBORDER_DETAIL_MD = jOBORDER_DETAIL_MD;
	}
	public int getJOBORDER_DETAIL_FD() {
		return JOBORDER_DETAIL_FD;
	}
	public void setJOBORDER_DETAIL_FD(int jOBORDER_DETAIL_FD) {
		JOBORDER_DETAIL_FD = jOBORDER_DETAIL_FD;
	}
	public String getJOBORDER_DETAIL_SSCPARTNO() {
		return JOBORDER_DETAIL_SSCPARTNO;
	}
	public void setJOBORDER_DETAIL_SSCPARTNO(String jOBORDER_DETAIL_SSCPARTNO) {
		JOBORDER_DETAIL_SSCPARTNO = jOBORDER_DETAIL_SSCPARTNO;
	}
	public String getJOBORDER_DETAIL_REV() {
		return JOBORDER_DETAIL_REV;
	}
	public void setJOBORDER_DETAIL_REV(String jOBORDER_DETAIL_REV) {
		JOBORDER_DETAIL_REV = jOBORDER_DETAIL_REV;
	}
	public String getJOBORDER_DETAIL_SERIALNO() {
		return JOBORDER_DETAIL_SERIALNO;
	}
	public void setJOBORDER_DETAIL_SERIALNO(String jOBORDER_DETAIL_SERIALNO) {
		JOBORDER_DETAIL_SERIALNO = jOBORDER_DETAIL_SERIALNO;
	}
	public int getJOBORDER_SUBTITLE_ID() {
		return JOBORDER_SUBTITLE_ID;
	}
	public void setJOBORDER_SUBTITLE_ID(int jOBORDER_SUBTITLE_ID) {
		JOBORDER_SUBTITLE_ID = jOBORDER_SUBTITLE_ID;
	}
	public String getJOBORDER_SUBTITLE_NAME() {
		return JOBORDER_SUBTITLE_NAME;
	}
	public void setJOBORDER_SUBTITLE_NAME(String jOBORDER_SUBTITLE_NAME) {
		JOBORDER_SUBTITLE_NAME = jOBORDER_SUBTITLE_NAME;
	}
	public int getJOBORDER_SUBTITLE_DIVISION() {
		return JOBORDER_SUBTITLE_DIVISION;
	}
	public void setJOBORDER_SUBTITLE_DIVISION(int jOBORDER_SUBTITLE_DIVISION) {
		JOBORDER_SUBTITLE_DIVISION = jOBORDER_SUBTITLE_DIVISION;
	}
	
	public int getORIGIN_EQUIPMENT_ID() {
		return ORIGIN_EQUIPMENT_ID;
	}
	public void setORIGIN_EQUIPMENT_ID(int oRIGIN_EQUIPMENT_ID) {
		ORIGIN_EQUIPMENT_ID = oRIGIN_EQUIPMENT_ID;
	}
}
