package com.lsh.testing05.graph.vo;

public class GraphVO {

	
	public int SPECIAL_CELL_CONTEXT_ID;
	public int SPECIAL_PROCESS_ID;
	public int SPECIAL_EQUIPMENT_ID;
	public int SPECIAL_BELLOWS_MATERIAL_ID;
	public int SPECIAL_OD_RANGE_ID;
	public int SPECIAL_THICKNESS_ID;
	public String SPECIAL_WORKTIME;
	
	public String SPECIAL_PROCESS_NAME;
	
	public String SPECIAL_EQUIPMENT_NAME;
	
	public String SPECIAL_BELLOWS_MATERIAL_NAME;
	
	public String SPECIAL_OD_RANGE_NAME;
	
	public String SPECIAL_THICKNESS_NAME;
	
	
	public int getSPECIAL_CELL_CONTEXT_ID() {
		return SPECIAL_CELL_CONTEXT_ID;
	}

	public void setSPECIAL_CELL_CONTEXT_ID(int sPECIAL_CELL_CONTEXT_ID) {
		SPECIAL_CELL_CONTEXT_ID = sPECIAL_CELL_CONTEXT_ID;
	}

	public int getSPECIAL_PROCESS_ID() {
		return SPECIAL_PROCESS_ID;
	}

	public void setSPECIAL_PROCESS_ID(int sPECIAL_PROCESS_ID) {
		SPECIAL_PROCESS_ID = sPECIAL_PROCESS_ID;
	}

	public int getSPECIAL_EQUIPMENT_ID() {
		return SPECIAL_EQUIPMENT_ID;
	}

	public void setSPECIAL_EQUIPMENT_ID(int sPECIAL_EQUIPMENT_ID) {
		SPECIAL_EQUIPMENT_ID = sPECIAL_EQUIPMENT_ID;
	}

	public int getSPECIAL_BELLOWS_MATERIAL_ID() {
		return SPECIAL_BELLOWS_MATERIAL_ID;
	}

	public void setSPECIAL_BELLOWS_MATERIAL_ID(int sPECIAL_BELLOWS_MATERIAL_ID) {
		SPECIAL_BELLOWS_MATERIAL_ID = sPECIAL_BELLOWS_MATERIAL_ID;
	}

	public int getSPECIAL_OD_RANGE_ID() {
		return SPECIAL_OD_RANGE_ID;
	}

	public void setSPECIAL_OD_RANGE_ID(int sPECIAL_OD_RANGE_ID) {
		SPECIAL_OD_RANGE_ID = sPECIAL_OD_RANGE_ID;
	}

	public int getSPECIAL_THICKNESS_ID() {
		return SPECIAL_THICKNESS_ID;
	}

	public void setSPECIAL_THICKNESS_ID(int sPECIAL_THICKNESS_ID) {
		SPECIAL_THICKNESS_ID = sPECIAL_THICKNESS_ID;
	}

	public String getSPECIAL_WORKTIME() {
		return SPECIAL_WORKTIME;
	}

	public void setSPECIAL_WORKTIME(String sPECIAL_WORKTIME) {
		SPECIAL_WORKTIME = sPECIAL_WORKTIME;
	}

	public String getSPECIAL_PROCESS_NAME() {
		return SPECIAL_PROCESS_NAME;
	}

	public void setSPECIAL_PROCESS_NAME(String sPECIAL_PROCESS_NAME) {
		SPECIAL_PROCESS_NAME = sPECIAL_PROCESS_NAME;
	}

	public String getSPECIAL_EQUIPMENT_NAME() {
		return SPECIAL_EQUIPMENT_NAME;
	}

	public void setSPECIAL_EQUIPMENT_NAME(String sPECIAL_EQUIPMENT_NAME) {
		SPECIAL_EQUIPMENT_NAME = sPECIAL_EQUIPMENT_NAME;
	}

	public String getSPECIAL_BELLOWS_MATERIAL_NAME() {
		return SPECIAL_BELLOWS_MATERIAL_NAME;
	}

	public void setSPECIAL_BELLOWS_MATERIAL_NAME(String sPECIAL_BELLOWS_MATERIAL_NAME) {
		SPECIAL_BELLOWS_MATERIAL_NAME = sPECIAL_BELLOWS_MATERIAL_NAME;
	}

	public String getSPECIAL_OD_RANGE_NAME() {
		return SPECIAL_OD_RANGE_NAME;
	}

	public void setSPECIAL_OD_RANGE_NAME(String sPECIAL_OD_RANGE_NAME) {
		SPECIAL_OD_RANGE_NAME = sPECIAL_OD_RANGE_NAME;
	}

	public String getSPECIAL_THICKNESS_NAME() {
		return SPECIAL_THICKNESS_NAME;
	}

	public void setSPECIAL_THICKNESS_NAME(String sPECIAL_THICKNESS_NAME) {
		SPECIAL_THICKNESS_NAME = sPECIAL_THICKNESS_NAME;
	}


}
