package com.lsh.testing.settingpresetuniquess.vo;

public class SettingpresetuniquessVO {
	
	//세팅 프리셋 공정 + 작업 특이사항에 쓰일 변수들
	
	public int SETTING_PRESET_PROCESS_UNIQUESS_ID;
	public int SETTONG_PRESET_PROCESS_ID;
	public int ORIGIN_UNIQUESS_ID;
	
	public int[] SETTING_PRESET_PROCESS_UNIQUESS_ID2;
	public int[] SETTONG_PRESET_PROCESS_ID2;
	public int[] ORIGIN_UNIQUESS_ID2;
	
	public int getSETTING_PRESET_PROCESS_UNIQUESS_ID() {
		return SETTING_PRESET_PROCESS_UNIQUESS_ID;
	}
	public void setSETTING_PRESET_PROCESS_UNIQUESS_ID(int sETTING_PRESET_PROCESS_UNIQUESS_ID) {
		SETTING_PRESET_PROCESS_UNIQUESS_ID = sETTING_PRESET_PROCESS_UNIQUESS_ID;
	}
	public int getSETTONG_PRESET_PROCESS_ID() {
		return SETTONG_PRESET_PROCESS_ID;
	}
	public void setSETTONG_PRESET_PROCESS_ID(int sETTONG_PRESET_PROCESS_ID) {
		SETTONG_PRESET_PROCESS_ID = sETTONG_PRESET_PROCESS_ID;
	}
	public int getORIGIN_UNIQUESS_ID() {
		return ORIGIN_UNIQUESS_ID;
	}
	public void setORIGIN_UNIQUESS_ID(int oRIGIN_UNIQUESS_ID) {
		ORIGIN_UNIQUESS_ID = oRIGIN_UNIQUESS_ID;
	}
	public int[] getSETTING_PRESET_PROCESS_UNIQUESS_ID2() {
		return SETTING_PRESET_PROCESS_UNIQUESS_ID2;
	}
	public void setSETTING_PRESET_PROCESS_UNIQUESS_ID2(int[] sETTING_PRESET_PROCESS_UNIQUESS_ID2) {
		SETTING_PRESET_PROCESS_UNIQUESS_ID2 = sETTING_PRESET_PROCESS_UNIQUESS_ID2;
	}
	public int[] getSETTONG_PRESET_PROCESS_ID2() {
		return SETTONG_PRESET_PROCESS_ID2;
	}
	public void setSETTONG_PRESET_PROCESS_ID2(int[] sETTONG_PRESET_PROCESS_ID2) {
		SETTONG_PRESET_PROCESS_ID2 = sETTONG_PRESET_PROCESS_ID2;
	}
	public int[] getORIGIN_UNIQUESS_ID2() {
		return ORIGIN_UNIQUESS_ID2;
	}
	public void setORIGIN_UNIQUESS_ID2(int[] oRIGIN_UNIQUESS_ID2) {
		ORIGIN_UNIQUESS_ID2 = oRIGIN_UNIQUESS_ID2;
	}
}
