package com.lsh.testing05.equip.vo;

public class EquipVO {
	
	//센서 설비
	public int EQUIPMENT_SENSOR_MATCHING_ID;
	public String EQUIPMENT_SENSOR_MATCHING_NUMBER;
	public String EQUIPMENT_SENSOR_MATCHING_NAME;
	public String EQUIPMENT_SENSOR_MATCHING_MODEL;
	public int EQUIPMENT_SENSOR_INDEX_ID;
	public String EQUIPMENT_SENSOR_INDEX_NAME;
	
	//원본 설비 관한 것들
	public int ORIGIN_EQUIPMENT_ID;
	public int ORIGIN_PROCESS_ID;
	public int PROCESS_MAIN_CATEGORY_ID;
	public String PROCESS_MAIN_CATEGORY_NAME;
	
	public String ORIGIN_EQUIPMENT_CONTEXT;
	public String ORIGIN_EQUIPMENT_NAME;
	public String ORIGIN_EQUIPMENT_CODE;
	public String ORIGIN_EQUIPMENT_MODELNAME;
	
	
	public String getPROCESS_MAIN_CATEGORY_NAME() {
		return PROCESS_MAIN_CATEGORY_NAME;
	}
	public void setPROCESS_MAIN_CATEGORY_NAME(String pROCESS_MAIN_CATEGORY_NAME) {
		PROCESS_MAIN_CATEGORY_NAME = pROCESS_MAIN_CATEGORY_NAME;
	}
	public String getEQUIPMENT_SENSOR_INDEX_NAME() {
		return EQUIPMENT_SENSOR_INDEX_NAME;
	}
	public void setEQUIPMENT_SENSOR_INDEX_NAME(String eQUIPMENT_SENSOR_INDEX_NAME) {
		EQUIPMENT_SENSOR_INDEX_NAME = eQUIPMENT_SENSOR_INDEX_NAME;
	}
	public int getEQUIPMENT_SENSOR_MATCHING_ID() {
		return EQUIPMENT_SENSOR_MATCHING_ID;
	}
	public void setEQUIPMENT_SENSOR_MATCHING_ID(int eQUIPMENT_SENSOR_MATCHING_ID) {
		EQUIPMENT_SENSOR_MATCHING_ID = eQUIPMENT_SENSOR_MATCHING_ID;
	}
	public String getEQUIPMENT_SENSOR_MATCHING_NUMBER() {
		return EQUIPMENT_SENSOR_MATCHING_NUMBER;
	}
	public void setEQUIPMENT_SENSOR_MATCHING_NUMBER(String eQUIPMENT_SENSOR_MATCHING_NUMBER) {
		EQUIPMENT_SENSOR_MATCHING_NUMBER = eQUIPMENT_SENSOR_MATCHING_NUMBER;
	}
	public String getEQUIPMENT_SENSOR_MATCHING_NAME() {
		return EQUIPMENT_SENSOR_MATCHING_NAME;
	}
	public void setEQUIPMENT_SENSOR_MATCHING_NAME(String eQUIPMENT_SENSOR_MATCHING_NAME) {
		EQUIPMENT_SENSOR_MATCHING_NAME = eQUIPMENT_SENSOR_MATCHING_NAME;
	}
	public String getEQUIPMENT_SENSOR_MATCHING_MODEL() {
		return EQUIPMENT_SENSOR_MATCHING_MODEL;
	}
	public void setEQUIPMENT_SENSOR_MATCHING_MODEL(String eQUIPMENT_SENSOR_MATCHING_MODEL) {
		EQUIPMENT_SENSOR_MATCHING_MODEL = eQUIPMENT_SENSOR_MATCHING_MODEL;
	}
	public int getEQUIPMENT_SENSOR_INDEX_ID() {
		return EQUIPMENT_SENSOR_INDEX_ID;
	}
	public void setEQUIPMENT_SENSOR_INDEX_ID(int eQUIPMENT_SENSOR_INDEX_ID) {
		EQUIPMENT_SENSOR_INDEX_ID = eQUIPMENT_SENSOR_INDEX_ID;
	}
	public String getORIGIN_EQUIPMENT_CONTEXT() {
		return ORIGIN_EQUIPMENT_CONTEXT;
	}
	public void setORIGIN_EQUIPMENT_CONTEXT(String oRIGIN_EQUIPMENT_CONTEXT) {
		ORIGIN_EQUIPMENT_CONTEXT = oRIGIN_EQUIPMENT_CONTEXT;
	}
	public int getORIGIN_EQUIPMENT_ID() {
		return ORIGIN_EQUIPMENT_ID;
	}
	public void setORIGIN_EQUIPMENT_ID(int oRIGIN_EQUIPMENT_ID) {
		ORIGIN_EQUIPMENT_ID = oRIGIN_EQUIPMENT_ID;
	}
	public int getPROCESS_MAIN_CATEGORY_ID() {
		return PROCESS_MAIN_CATEGORY_ID;
	}
	public void setPROCESS_MAIN_CATEGORY_ID(int pROCESS_MAIN_CATEGORY_ID) {
		PROCESS_MAIN_CATEGORY_ID = pROCESS_MAIN_CATEGORY_ID;
	}
	public int getORIGIN_PROCESS_ID() {
		return ORIGIN_PROCESS_ID;
	}
	public void setORIGIN_PROCESS_ID(int oRIGIN_PROCESS_ID) {
		ORIGIN_PROCESS_ID = oRIGIN_PROCESS_ID;
	}
	public String getORIGIN_EQUIPMENT_NAME() {
		return ORIGIN_EQUIPMENT_NAME;
	}
	public void setORIGIN_EQUIPMENT_NAME(String oRIGIN_EQUIPMENT_NAME) {
		ORIGIN_EQUIPMENT_NAME = oRIGIN_EQUIPMENT_NAME;
	}
	public String getORIGIN_EQUIPMENT_CODE() {
		return ORIGIN_EQUIPMENT_CODE;
	}
	public void setORIGIN_EQUIPMENT_CODE(String oRIGIN_EQUIPMENT_CODE) {
		ORIGIN_EQUIPMENT_CODE = oRIGIN_EQUIPMENT_CODE;
	}
	public String getORIGIN_EQUIPMENT_MODELNAME() {
		return ORIGIN_EQUIPMENT_MODELNAME;
	}
	public void setORIGIN_EQUIPMENT_MODELNAME(String oRIGIN_EQUIPMENT_MODELNAME) {
		ORIGIN_EQUIPMENT_MODELNAME = oRIGIN_EQUIPMENT_MODELNAME;
	}
}
