package com.lsh.testing05.file.vo;

public class FileVO {

	public int SETTING_PRESET_FILE_MANAGEMENT_ID;
	public int SETTING_PRESET_ID;
	public int SETTING_PRESET_CT_FILE_ID;
	public int SETTING_PRESET_CT_FILE_REGISTER_ID;
	public int SETTING_PRESET_CT_FILE_DIVISION_ID;
	public String SETTING_PRESET_FILE_MANAGEMENT_NAME;
	public String SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	
	public int[] SETTING_PRESET_FILE_MANAGEMENT_ID2;
	public int[] SETTING_PRESET_ID2;
	public int[] SETTING_PRESET_CT_FILE_ID2;
	public int[] SETTING_PRESET_CT_FILE_REGISTER_ID2;
	public int[] SETTING_PRESET_CT_FILE_DIVISION_ID2;
	public String[] SETTING_PRESET_FILE_MANAGEMENT_NAME2;
	public String[]	SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	
	public int getSETTING_PRESET_FILE_MANAGEMENT_ID() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID(int sETTING_PRESET_FILE_MANAGEMENT_ID) {
		SETTING_PRESET_FILE_MANAGEMENT_ID = sETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public int getSETTING_PRESET_ID() {
		return SETTING_PRESET_ID;
	}
	public void setSETTING_PRESET_ID(int sETTING_PRESET_ID) {
		SETTING_PRESET_ID = sETTING_PRESET_ID;
	}
	public int getSETTING_PRESET_CT_FILE_ID() {
		return SETTING_PRESET_CT_FILE_ID;
	}
	public void setSETTING_PRESET_CT_FILE_ID(int sETTING_PRESET_CT_FILE_ID) {
		SETTING_PRESET_CT_FILE_ID = sETTING_PRESET_CT_FILE_ID;
	}
	public int getSETTING_PRESET_CT_FILE_REGISTER_ID() {
		return SETTING_PRESET_CT_FILE_REGISTER_ID;
	}
	public void setSETTING_PRESET_CT_FILE_REGISTER_ID(int sETTING_PRESET_CT_FILE_REGISTER_ID) {
		SETTING_PRESET_CT_FILE_REGISTER_ID = sETTING_PRESET_CT_FILE_REGISTER_ID;
	}
	public int getSETTING_PRESET_CT_FILE_DIVISION_ID() {
		return SETTING_PRESET_CT_FILE_DIVISION_ID;
	}
	public void setSETTING_PRESET_CT_FILE_DIVISION_ID(int sETTING_PRESET_CT_FILE_DIVISION_ID) {
		SETTING_PRESET_CT_FILE_DIVISION_ID = sETTING_PRESET_CT_FILE_DIVISION_ID;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_NAME() {
		return SETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_NAME(String sETTING_PRESET_FILE_MANAGEMENT_NAME) {
		SETTING_PRESET_FILE_MANAGEMENT_NAME = sETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY() {
		return SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY(String sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY) {
		SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY = sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public int[] getSETTING_PRESET_FILE_MANAGEMENT_ID2() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID2(int[] sETTING_PRESET_FILE_MANAGEMENT_ID2) {
		SETTING_PRESET_FILE_MANAGEMENT_ID2 = sETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public int[] getSETTING_PRESET_ID2() {
		return SETTING_PRESET_ID2;
	}
	public void setSETTING_PRESET_ID2(int[] sETTING_PRESET_ID2) {
		SETTING_PRESET_ID2 = sETTING_PRESET_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_ID2() {
		return SETTING_PRESET_CT_FILE_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_ID2(int[] sETTING_PRESET_CT_FILE_ID2) {
		SETTING_PRESET_CT_FILE_ID2 = sETTING_PRESET_CT_FILE_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_REGISTER_ID2() {
		return SETTING_PRESET_CT_FILE_REGISTER_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_REGISTER_ID2(int[] sETTING_PRESET_CT_FILE_REGISTER_ID2) {
		SETTING_PRESET_CT_FILE_REGISTER_ID2 = sETTING_PRESET_CT_FILE_REGISTER_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_DIVISION_ID2() {
		return SETTING_PRESET_CT_FILE_DIVISION_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_DIVISION_ID2(int[] sETTING_PRESET_CT_FILE_DIVISION_ID2) {
		SETTING_PRESET_CT_FILE_DIVISION_ID2 = sETTING_PRESET_CT_FILE_DIVISION_ID2;
	}
	public String[] getSETTING_PRESET_FILE_MANAGEMENT_NAME2() {
		return SETTING_PRESET_FILE_MANAGEMENT_NAME2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_NAME2(String[] sETTING_PRESET_FILE_MANAGEMENT_NAME2) {
		SETTING_PRESET_FILE_MANAGEMENT_NAME2 = sETTING_PRESET_FILE_MANAGEMENT_NAME2;
	}
	public String[] getSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2() {
		return SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2(String[] sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2) {
		SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2 = sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	}
	
	
}
