package com.lsh.testing05.settingpreset.vo;

import java.util.Date;
import java.util.List;

import org.json.simple.JSONObject;


public class SettingpresetVO {

	//자주검사 전체 체크 변수
	public String SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK;
	public String[] SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2;
	
	//Copy 반환 타입
	public int CopyPresetId;
	
	//SETTING_PRESET_FILE 테이블 변수
	public int SETTING_PRESET_FILE_MANAGEMENT_ID;
	
	public int JOBORDER_FILE_TYPE_ID;
	public String SETTING_PRESET_FILE_MANAGEMENT_NAME;
	public String SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	public String SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;

	public int[] SETTING_PRESET_FILE_MANAGEMENT_ID2;
	public int[] SETTING_PRESET_CT_FILE_ID2;
	public int[] SETTING_PRESET_CT_FILE_REGISTER_ID2;
	public int[] SETTING_PRESET_CT_FILE_DIVISION_ID2;
	public String[] SETTING_PRESET_FILE_MANAGEMENT_NAME2;
	public String[]	SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	
	public int[] JOBORDER_FILE_TYPE_ID2;
	
	//치환 변수
	public String SETTING_PRESET_PROCESS_ID_ARRAY;
	public String SETTING_PRESET_PROCESS_INDEX_ARRAY;
	public String ORIGIN_PROCESS_ID_ARRAY;
	

	//SETTING_PRESET 테이블 변수
	public int SETTING_PRESET_ID;


	public int USE_DIVISION_ID;
	public int ORIGIN_ACCOUNT_ID;
	public int ORIGIN_ACCOUNT_DIVISION_ID;
	public String SETTING_PRESET_NAME;
	public Date SETTING_PRESET_CREATEDATE;
	public String ConvertSETTING_PRESET_CREATEDATE;


	public int ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID;
	
	
	//SETTING_PRESET 테이블에 여러개 넣기 위한 배열 변수
	public int[] SETTING_PRESET_ID2;
	public int[] USE_DIVISION_ID2;
	public int[] ORIGIN_ACCOUNT_ID2;
	public int[] ORIGIN_ACCOUNT_DIVISION_ID2;
	public String[] SETTING_PRESET_NAME2;
	public Date[] SETTING_PRESET_CREATEDATE2;
	public int[] ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2;
	
	//SETTING_PRESET_PROCESS 테이블 변수
	public int SETTING_PRESET_PROCESS_ID;
	public int ORIGIN_PROCESS_ID;
	public int SETTING_PRESET_PROCESS_INDEX;
	
	//SETTING_PRESET_PROCESS 공정 시간 변수
	public float SETTING_PRESET_PROCESS_WORKTIME;
	public float[] SETTING_PRESET_PROCESS_WORKTIME2;
	
	//SETTING_PRESET_PROCESS 자주검사 xml 파일
	public String SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	public String[] SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2;
	
	//SETTING_PRESET_PROCESS 자주검사 xml 여부
	public int SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	public int[] SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2;
	
	//SETTING_PRESET_PROCESS 파일 구분 변수명
	public int CT_FILE_REGISTER_ID;
	
	//SETTING_PRESET_PROCESS 외주 거래처명 사업자 번호
	public int SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER;
	public int[] SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2;
	
	public String SETTING_PRESET_PROCESS_CUSTOMER_NAME;
	public String[] SETTING_PRESET_PROCESS_CUSTOMER_NAME2;
	
	public String SETTING_PRESET_PROCESS_CUSTOMER_NUMBER;
	public String[] SETTING_PRESET_PROCESS_CUSTOMER_NUMBER2;

	//SETTING_PRESET_PROCESS 테이블에 여러개 넣기 위한 배열 변수
	public int[] SETTING_PRESET_PROCESS_ID2;
	public int[] ORIGIN_PROCESS_ID2;
	public int[] SETTING_PRESET_PROCESS_INDEX2;
	
	
	//그외 다른 테이블에서 가져와야되는 Inner join을 위해 필요한 것들
	public String USE_DIVISION_NAME;
	public String ORIGIN_ACCOUNT_MEMBERNAME;
	public String ORIGIN_PROCESS_NAME;
	
	//세팅 프리셋 공정 + 작업 특이사항에 쓰일 변수들
	
	public int[] SETTING_PRESET_PROCESS_UNIQUESS_ID2;
	
	public int[][] SETTING_PRESET_PROCESS_UNIQUESS_ID3;
	
	public int SETTING_PRESET_PROCESS_UNIQUESS_ID;
	public int SETTONG_PRESET_PROCESS_ID;
	public int ORIGIN_UNIQUESS_ID;
	
	public int[] ORIGIN_UNIQUESS_ID2;
	public Integer[][] ORIGIN_UNIQUESS_ID3;
	
	public String ORIGIN_UNIQUESS_CONTEXT;
	
	//PROCESS 변수
	public int PROCESS_MAIN_CATEGORY_ID;
	public String ORIGIN_PROCESS_CODE;
	public int ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	public String ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	public int ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	public String ORIGIN_PROCESS_CUSTOMER_NAME;
	public String ORIGIN_PROCESS_CUSTOMER_NUMBER;
	
	
	public String getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK(
			String sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK;
	}
	public String[] getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2(
			String[] sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2 = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_CHECK2;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY() {
		return SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY(String sETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY) {
		SETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY = sETTING_PRESET_FILE_MANAGEMENT_DB_DIRECTORY;
	}
	public String getConvertSETTING_PRESET_CREATEDATE() {
		return ConvertSETTING_PRESET_CREATEDATE;
	}
	public void setConvertSETTING_PRESET_CREATEDATE(String convertSETTING_PRESET_CREATEDATE) {
		ConvertSETTING_PRESET_CREATEDATE = convertSETTING_PRESET_CREATEDATE;
	}
	public int getCopyPresetId() {
		return CopyPresetId;
	}
	public void setCopyPresetId(int copyPresetId) {
		CopyPresetId = copyPresetId;
	}
	public int getPROCESS_MAIN_CATEGORY_ID() {
		return PROCESS_MAIN_CATEGORY_ID;
	}
	public void setPROCESS_MAIN_CATEGORY_ID(int pROCESS_MAIN_CATEGORY_ID) {
		PROCESS_MAIN_CATEGORY_ID = pROCESS_MAIN_CATEGORY_ID;
	}
	public String getORIGIN_PROCESS_CODE() {
		return ORIGIN_PROCESS_CODE;
	}
	public void setORIGIN_PROCESS_CODE(String oRIGIN_PROCESS_CODE) {
		ORIGIN_PROCESS_CODE = oRIGIN_PROCESS_CODE;
	}
	public int getORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER() {
		return ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	public void setORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER(int oRIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER) {
		ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER = oRIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	public String getORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY() {
		return ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public void setORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY(String oRIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY) {
		ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY = oRIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public int getORIGIN_PROCESS_OUTSOURCING_REGISTER() {
		return ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public void setORIGIN_PROCESS_OUTSOURCING_REGISTER(int oRIGIN_PROCESS_OUTSOURCING_REGISTER) {
		ORIGIN_PROCESS_OUTSOURCING_REGISTER = oRIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NAME() {
		return ORIGIN_PROCESS_CUSTOMER_NAME;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NAME(String oRIGIN_PROCESS_CUSTOMER_NAME) {
		ORIGIN_PROCESS_CUSTOMER_NAME = oRIGIN_PROCESS_CUSTOMER_NAME;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NUMBER() {
		return ORIGIN_PROCESS_CUSTOMER_NUMBER;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NUMBER(String oRIGIN_PROCESS_CUSTOMER_NUMBER) {
		ORIGIN_PROCESS_CUSTOMER_NUMBER = oRIGIN_PROCESS_CUSTOMER_NUMBER;
	}
	public String getORIGIN_PROCESS_ID_ARRAY() {
		return ORIGIN_PROCESS_ID_ARRAY;
	}
	public void setORIGIN_PROCESS_ID_ARRAY(String oRIGIN_PROCESS_ID_ARRAY) {
		ORIGIN_PROCESS_ID_ARRAY = oRIGIN_PROCESS_ID_ARRAY;
	}
	public String getSETTING_PRESET_PROCESS_ID_ARRAY() {
		return SETTING_PRESET_PROCESS_ID_ARRAY;
	}
	public void setSETTING_PRESET_PROCESS_ID_ARRAY(String sETTING_PRESET_PROCESS_ID_ARRAY) {
		SETTING_PRESET_PROCESS_ID_ARRAY = sETTING_PRESET_PROCESS_ID_ARRAY;
	}
	public String getSETTING_PRESET_PROCESS_INDEX_ARRAY() {
		return SETTING_PRESET_PROCESS_INDEX_ARRAY;
	}
	public void setSETTING_PRESET_PROCESS_INDEX_ARRAY(String sETTING_PRESET_PROCESS_INDEX_ARRAY) {
		SETTING_PRESET_PROCESS_INDEX_ARRAY = sETTING_PRESET_PROCESS_INDEX_ARRAY;
	}
	public int[] getJOBORDER_FILE_TYPE_ID2() {
		return JOBORDER_FILE_TYPE_ID2;
	}
	public void setJOBORDER_FILE_TYPE_ID2(int[] jOBORDER_FILE_TYPE_ID2) {
		JOBORDER_FILE_TYPE_ID2 = jOBORDER_FILE_TYPE_ID2;
	}
	public int getJOBORDER_FILE_TYPE_ID() {
		return JOBORDER_FILE_TYPE_ID;
	}
	public void setJOBORDER_FILE_TYPE_ID(int jOBORDER_FILE_TYPE_ID) {
		JOBORDER_FILE_TYPE_ID = jOBORDER_FILE_TYPE_ID;
	}
	public int[][] getSETTING_PRESET_PROCESS_UNIQUESS_ID3() {
		return SETTING_PRESET_PROCESS_UNIQUESS_ID3;
	}
	public void setSETTING_PRESET_PROCESS_UNIQUESS_ID3(int[][] sETTING_PRESET_PROCESS_UNIQUESS_ID3) {
		SETTING_PRESET_PROCESS_UNIQUESS_ID3 = sETTING_PRESET_PROCESS_UNIQUESS_ID3;
	}
	public int getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER(
			int sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	public int[] getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2(
			int[] sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2 = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_REGISTER2;
	}
	public float[] getSETTING_PRESET_PROCESS_WORKTIME2() {
		return SETTING_PRESET_PROCESS_WORKTIME2;
	}
	public void setSETTING_PRESET_PROCESS_WORKTIME2(float[] sETTING_PRESET_PROCESS_WORKTIME2) {
		SETTING_PRESET_PROCESS_WORKTIME2 = sETTING_PRESET_PROCESS_WORKTIME2;
	}
	public String[] getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2(
			String[] sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2 = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY2;
	}
	public int[] getSETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2() {
		return SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2;
	}
	public void setSETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2(int[] sETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2) {
		SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2 = sETTING_PRESET_PROCESS_OUTSOURCING_REGISTER2;
	}
	public String[] getSETTING_PRESET_PROCESS_CUSTOMER_NAME2() {
		return SETTING_PRESET_PROCESS_CUSTOMER_NAME2;
	}
	public void setSETTING_PRESET_PROCESS_CUSTOMER_NAME2(String[] sETTING_PRESET_PROCESS_CUSTOMER_NAME2) {
		SETTING_PRESET_PROCESS_CUSTOMER_NAME2 = sETTING_PRESET_PROCESS_CUSTOMER_NAME2;
	}
	public String[] getSETTING_PRESET_PROCESS_CUSTOMER_NUMBER2() {
		return SETTING_PRESET_PROCESS_CUSTOMER_NUMBER2;
	}
	public void setSETTING_PRESET_PROCESS_CUSTOMER_NUMBER2(String[] sETTING_PRESET_PROCESS_CUSTOMER_NUMBER2) {
		SETTING_PRESET_PROCESS_CUSTOMER_NUMBER2 = sETTING_PRESET_PROCESS_CUSTOMER_NUMBER2;
	}
	public int getCT_FILE_REGISTER_ID() {
		return CT_FILE_REGISTER_ID;
	}
	public void setCT_FILE_REGISTER_ID(int cT_FILE_REGISTER_ID) {
		CT_FILE_REGISTER_ID = cT_FILE_REGISTER_ID;
	}
	public float getSETTING_PRESET_PROCESS_WORKTIME() {
		return SETTING_PRESET_PROCESS_WORKTIME;
	}
	public void setSETTING_PRESET_PROCESS_WORKTIME(float sETTING_PRESET_PROCESS_WORKTIME) {
		SETTING_PRESET_PROCESS_WORKTIME = sETTING_PRESET_PROCESS_WORKTIME;
	}
	public String getSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY() {
		return SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public void setSETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY(
			String sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY) {
		SETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY = sETTING_PRESET_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public int getSETTING_PRESET_PROCESS_OUTSOURCING_REGISTER() {
		return SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER;
	}
	public void setSETTING_PRESET_PROCESS_OUTSOURCING_REGISTER(int sETTING_PRESET_PROCESS_OUTSOURCING_REGISTER) {
		SETTING_PRESET_PROCESS_OUTSOURCING_REGISTER = sETTING_PRESET_PROCESS_OUTSOURCING_REGISTER;
	}
	public String getSETTING_PRESET_PROCESS_CUSTOMER_NAME() {
		return SETTING_PRESET_PROCESS_CUSTOMER_NAME;
	}
	public void setSETTING_PRESET_PROCESS_CUSTOMER_NAME(String sETTING_PRESET_PROCESS_CUSTOMER_NAME) {
		SETTING_PRESET_PROCESS_CUSTOMER_NAME = sETTING_PRESET_PROCESS_CUSTOMER_NAME;
	}
	public String getSETTING_PRESET_PROCESS_CUSTOMER_NUMBER() {
		return SETTING_PRESET_PROCESS_CUSTOMER_NUMBER;
	}
	public void setSETTING_PRESET_PROCESS_CUSTOMER_NUMBER(String sETTING_PRESET_PROCESS_CUSTOMER_NUMBER) {
		SETTING_PRESET_PROCESS_CUSTOMER_NUMBER = sETTING_PRESET_PROCESS_CUSTOMER_NUMBER;
	}
	
	public int[] getSETTING_PRESET_PROCESS_UNIQUESS_ID2() {
		return SETTING_PRESET_PROCESS_UNIQUESS_ID2;
	}
	public void setSETTING_PRESET_PROCESS_UNIQUESS_ID2(int[] sETTING_PRESET_PROCESS_UNIQUESS_ID2) {
		SETTING_PRESET_PROCESS_UNIQUESS_ID2 = sETTING_PRESET_PROCESS_UNIQUESS_ID2;
	}
	public String getORIGIN_UNIQUESS_CONTEXT() {
		return ORIGIN_UNIQUESS_CONTEXT;
	}
	public void setORIGIN_UNIQUESS_CONTEXT(String oRIGIN_UNIQUESS_CONTEXT) {
		ORIGIN_UNIQUESS_CONTEXT = oRIGIN_UNIQUESS_CONTEXT;
	}
	public Integer[][] getORIGIN_UNIQUESS_ID3() {
		return ORIGIN_UNIQUESS_ID3;
	}
	public void setORIGIN_UNIQUESS_ID3(Integer[][] oRIGIN_UNIQUESS_ID3) {
		ORIGIN_UNIQUESS_ID3 = oRIGIN_UNIQUESS_ID3;
	}

	public List<SettingpresetVO> list;
	
	public int getSETTING_PRESET_PROCESS_ID() {
		return SETTING_PRESET_PROCESS_ID;
	}
	public void setSETTING_PRESET_PROCESS_ID(int sETTING_PRESET_PROCESS_ID) {
		SETTING_PRESET_PROCESS_ID = sETTING_PRESET_PROCESS_ID;
	}
	public int[] getSETTING_PRESET_PROCESS_ID2() {
		return SETTING_PRESET_PROCESS_ID2;
	}
	public void setSETTING_PRESET_PROCESS_ID2(int[] sETTING_PRESET_PROCESS_ID2) {
		SETTING_PRESET_PROCESS_ID2 = sETTING_PRESET_PROCESS_ID2;
	}
	public int[] getORIGIN_PROCESS_ID2() {
		return ORIGIN_PROCESS_ID2;
	}
	public void setORIGIN_PROCESS_ID2(int[] oRIGIN_PROCESS_ID2) {
		ORIGIN_PROCESS_ID2 = oRIGIN_PROCESS_ID2;
	}
	public int[] getSETTING_PRESET_PROCESS_INDEX2() {
		return SETTING_PRESET_PROCESS_INDEX2;
	}
	public void setSETTING_PRESET_PROCESS_INDEX2(int[] sETTING_PRESET_PROCESS_INDEX2) {
		SETTING_PRESET_PROCESS_INDEX2 = sETTING_PRESET_PROCESS_INDEX2;
	}
	public int getORIGIN_PROCESS_ID() {
		return ORIGIN_PROCESS_ID;
	}
	public void setORIGIN_PROCESS_ID(int oRIGIN_PROCESS_ID) {
		ORIGIN_PROCESS_ID = oRIGIN_PROCESS_ID;
	}
	public int getSETTING_PRESET_PROCESS_INDEX() {
		return SETTING_PRESET_PROCESS_INDEX;
	}
	public void setSETTING_PRESET_PROCESS_INDEX(int sETTING_PRESET_PROCESS_INDEX) {
		SETTING_PRESET_PROCESS_INDEX = sETTING_PRESET_PROCESS_INDEX;
	}
	public String getUSE_DIVISION_NAME() {
		return USE_DIVISION_NAME;
	}
	public void setUSE_DIVISION_NAME(String uSE_DIVISION_NAME) {
		USE_DIVISION_NAME = uSE_DIVISION_NAME;
	}
	public String getORIGIN_PROCESS_NAME() {
		return ORIGIN_PROCESS_NAME;
	}
	public void setORIGIN_PROCESS_NAME(String oRIGIN_PROCESS_NAME) {
		ORIGIN_PROCESS_NAME = oRIGIN_PROCESS_NAME;
	}
	public int[] getSETTING_PRESET_ID2() {
		return SETTING_PRESET_ID2;
	}
	public void setSETTING_PRESET_ID2(int[] sETTING_PRESET_ID2) {
		SETTING_PRESET_ID2 = sETTING_PRESET_ID2;
	}
	public int[] getUSE_DIVISION_ID2() {
		return USE_DIVISION_ID2;
	}
	public void setUSE_DIVISION_ID2(int[] uSE_DIVISION_ID2) {
		USE_DIVISION_ID2 = uSE_DIVISION_ID2;
	}
	public int[] getORIGIN_ACCOUNT_ID2() {
		return ORIGIN_ACCOUNT_ID2;
	}
	public void setORIGIN_ACCOUNT_ID2(int[] oRIGIN_ACCOUNT_ID2) {
		ORIGIN_ACCOUNT_ID2 = oRIGIN_ACCOUNT_ID2;
	}
	public int[] getORIGIN_ACCOUNT_DIVISION_ID2() {
		return ORIGIN_ACCOUNT_DIVISION_ID2;
	}
	public void setORIGIN_ACCOUNT_DIVISION_ID2(int[] oRIGIN_ACCOUNT_DIVISION_ID2) {
		ORIGIN_ACCOUNT_DIVISION_ID2 = oRIGIN_ACCOUNT_DIVISION_ID2;
	}
	public String[] getSETTING_PRESET_NAME2() {
		return SETTING_PRESET_NAME2;
	}
	public void setSETTING_PRESET_NAME2(String[] sETTING_PRESET_NAME2) {
		SETTING_PRESET_NAME2 = sETTING_PRESET_NAME2;
	}
	public Date[] getSETTING_PRESET_CREATEDATE2() {
		return SETTING_PRESET_CREATEDATE2;
	}
	public void setSETTING_PRESET_CREATEDATE2(Date[] sETTING_PRESET_CREATEDATE2) {
		SETTING_PRESET_CREATEDATE2 = sETTING_PRESET_CREATEDATE2;
	}
	public int[] getORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2() {
		return ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2;
	}
	public void setORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2(int[] oRIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2) {
		ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2 = oRIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID2;
	}
	public List<SettingpresetVO> getList() {
		return list;
	}
	public void setList(List<SettingpresetVO> list) {
		this.list = list;
	}
	public int getSETTING_PRESET_ID() {
		return SETTING_PRESET_ID;
	}
	public void setSETTING_PRESET_ID(int sETTING_PRESET_ID) {
		SETTING_PRESET_ID = sETTING_PRESET_ID;
	}
	public int getUSE_DIVISION_ID() {
		return USE_DIVISION_ID;
	}
	public void setUSE_DIVISION_ID(int uSE_DIVISION_ID) {
		USE_DIVISION_ID = uSE_DIVISION_ID;
	}
	public int getORIGIN_ACCOUNT_ID() {
		return ORIGIN_ACCOUNT_ID;
	}
	public void setORIGIN_ACCOUNT_ID(int oRIGIN_ACCOUNT_ID) {
		ORIGIN_ACCOUNT_ID = oRIGIN_ACCOUNT_ID;
	}
	public int getORIGIN_ACCOUNT_DIVISION_ID() {
		return ORIGIN_ACCOUNT_DIVISION_ID;
	}
	public void setORIGIN_ACCOUNT_DIVISION_ID(int oRIGIN_ACCOUNT_DIVISION_ID) {
		ORIGIN_ACCOUNT_DIVISION_ID = oRIGIN_ACCOUNT_DIVISION_ID;
	}
	public String getSETTING_PRESET_NAME() {
		return SETTING_PRESET_NAME;
	}
	public void setSETTING_PRESET_NAME(String sETTING_PRESET_NAME) {
		SETTING_PRESET_NAME = sETTING_PRESET_NAME;
	}
	public Date getSETTING_PRESET_CREATEDATE() {
		return SETTING_PRESET_CREATEDATE;
	}
	public void setSETTING_PRESET_CREATEDATE(Date sETTING_PRESET_CREATEDATE) {
		SETTING_PRESET_CREATEDATE = sETTING_PRESET_CREATEDATE;
	}
	public int getORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID() {
		return ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID;
	}
	public void setORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID(int oRIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID) {
		ORIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID = oRIGIN_ACCOUNT_EMPLOYMENT_STATUS_ID;
	}
	public String getORIGIN_ACCOUNT_MEMBERNAME() {
		return ORIGIN_ACCOUNT_MEMBERNAME;
	}
	public void setORIGIN_ACCOUNT_MEMBERNAME(String oRIGIN_ACCOUNT_MEMBERNAME) {
		ORIGIN_ACCOUNT_MEMBERNAME = oRIGIN_ACCOUNT_MEMBERNAME;
	}
	public int getSETTING_PRESET_FILE_MANAGEMENT_ID() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID(int sETTING_PRESET_FILE_MANAGEMENT_ID) {
		SETTING_PRESET_FILE_MANAGEMENT_ID = sETTING_PRESET_FILE_MANAGEMENT_ID;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_NAME() {
		return SETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_NAME(String sETTING_PRESET_FILE_MANAGEMENT_NAME) {
		SETTING_PRESET_FILE_MANAGEMENT_NAME = sETTING_PRESET_FILE_MANAGEMENT_NAME;
	}
	public String getSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY() {
		return SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY(String sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY) {
		SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY = sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY;
	}
	public int[] getSETTING_PRESET_FILE_MANAGEMENT_ID2() {
		return SETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_ID2(int[] sETTING_PRESET_FILE_MANAGEMENT_ID2) {
		SETTING_PRESET_FILE_MANAGEMENT_ID2 = sETTING_PRESET_FILE_MANAGEMENT_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_ID2() {
		return SETTING_PRESET_CT_FILE_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_ID2(int[] sETTING_PRESET_CT_FILE_ID2) {
		SETTING_PRESET_CT_FILE_ID2 = sETTING_PRESET_CT_FILE_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_REGISTER_ID2() {
		return SETTING_PRESET_CT_FILE_REGISTER_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_REGISTER_ID2(int[] sETTING_PRESET_CT_FILE_REGISTER_ID2) {
		SETTING_PRESET_CT_FILE_REGISTER_ID2 = sETTING_PRESET_CT_FILE_REGISTER_ID2;
	}
	public int[] getSETTING_PRESET_CT_FILE_DIVISION_ID2() {
		return SETTING_PRESET_CT_FILE_DIVISION_ID2;
	}
	public void setSETTING_PRESET_CT_FILE_DIVISION_ID2(int[] sETTING_PRESET_CT_FILE_DIVISION_ID2) {
		SETTING_PRESET_CT_FILE_DIVISION_ID2 = sETTING_PRESET_CT_FILE_DIVISION_ID2;
	}
	public String[] getSETTING_PRESET_FILE_MANAGEMENT_NAME2() {
		return SETTING_PRESET_FILE_MANAGEMENT_NAME2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_NAME2(String[] sETTING_PRESET_FILE_MANAGEMENT_NAME2) {
		SETTING_PRESET_FILE_MANAGEMENT_NAME2 = sETTING_PRESET_FILE_MANAGEMENT_NAME2;
	}
	public String[] getSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2() {
		return SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	}
	public void setSETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2(String[] sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2) {
		SETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2 = sETTING_PRESET_FILE_MANAGEMENT_DIRECTORY2;
	}
	public int getSETTING_PRESET_PROCESS_UNIQUESS_ID() {
		return SETTING_PRESET_PROCESS_UNIQUESS_ID;
	}
	public void setSETTING_PRESET_PROCESS_UNIQUESS_ID(int sETTING_PRESET_PROCESS_UNIQUESS_ID) {
		SETTING_PRESET_PROCESS_UNIQUESS_ID = sETTING_PRESET_PROCESS_UNIQUESS_ID;
	}
	public int getSETTONG_PRESET_PROCESS_ID() {
		return SETTONG_PRESET_PROCESS_ID;
	}
	public void setSETTONG_PRESET_PROCESS_ID(int sETTONG_PRESET_PROCESS_ID) {
		SETTONG_PRESET_PROCESS_ID = sETTONG_PRESET_PROCESS_ID;
	}
	public int getORIGIN_UNIQUESS_ID() {
		return ORIGIN_UNIQUESS_ID;
	}
	public void setORIGIN_UNIQUESS_ID(int oRIGIN_UNIQUESS_ID) {
		ORIGIN_UNIQUESS_ID = oRIGIN_UNIQUESS_ID;
	}
	public int[] getORIGIN_UNIQUESS_ID2() {
		return ORIGIN_UNIQUESS_ID2;
	}
	public void setORIGIN_UNIQUESS_ID2(int[] oRIGIN_UNIQUESS_ID2) {
		ORIGIN_UNIQUESS_ID2 = oRIGIN_UNIQUESS_ID2;
	}

}
