package com.lsh.testing05.process.vo;

public class ProcessVO {

	public String getORIGIN_EQUIPMENT_CONTEXT() {
		return ORIGIN_EQUIPMENT_CONTEXT;
	}
	public void setORIGIN_EQUIPMENT_CONTEXT(String oRIGIN_EQUIPMENT_CONTEXT) {
		ORIGIN_EQUIPMENT_CONTEXT = oRIGIN_EQUIPMENT_CONTEXT;
	}
	public int getJOBORDER_FORM_DETAIL_MATCHING() {
		return JOBORDER_FORM_DETAIL_MATCHING;
	}
	public void setJOBORDER_FORM_DETAIL_MATCHING(int jOBORDER_FORM_DETAIL_MATCHING) {
		JOBORDER_FORM_DETAIL_MATCHING = jOBORDER_FORM_DETAIL_MATCHING;
	}
	public int getJOBORDER_FORM_DETAIL_ID() {
		return JOBORDER_FORM_DETAIL_ID;
	}
	public void setJOBORDER_FORM_DETAIL_ID(int jOBORDER_FORM_DETAIL_ID) {
		JOBORDER_FORM_DETAIL_ID = jOBORDER_FORM_DETAIL_ID;
	}
	public String getJOBORDER_FORM_DETAIL_NAME() {
		return JOBORDER_FORM_DETAIL_NAME;
	}
	public void setJOBORDER_FORM_DETAIL_NAME(String jOBORDER_FORM_DETAIL_NAME) {
		JOBORDER_FORM_DETAIL_NAME = jOBORDER_FORM_DETAIL_NAME;
	}
	public String getJOBORDER_FORM_DETAIL_FILENAME() {
		return JOBORDER_FORM_DETAIL_FILENAME;
	}
	public void setJOBORDER_FORM_DETAIL_FILENAME(String jOBORDER_FORM_DETAIL_FILENAME) {
		JOBORDER_FORM_DETAIL_FILENAME = jOBORDER_FORM_DETAIL_FILENAME;
	}
	public String ORIGIN_EQUIPMENT_CONTEXT;
	
	//공정
	public int ORIGIN_PROCESS_ID;
	public String ORIGIN_PROCESS_NAME;
	public String ORIGIN_PROCESS_CODE;
	public int ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	public String ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	public int ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	public String ORIGIN_PROCESS_CUSTOMER_NAME;
	public String ORIGIN_PROCESS_CUSTOMER_NUMBER;
	
	//공정 매칭용 변수
	public int JOBORDER_FORM_DETAIL_MATCHING;
	public int JOBORDER_FORM_DETAIL_ID;
	
	//공정 파일 넣어야되는 테이블
	public String JOBORDER_FORM_DETAIL_NAME;
	public String JOBORDER_FORM_DETAIL_FILENAME;
	
	//대분류
	public int PROCESS_MAIN_CATEGORY_ID;
	public String PROCESS_MAIN_CATEGORY_NAME;
	
	//설비
	public int ORIGIN_EQUIPMENT_ID;
	public String ORIGIN_EQUIPMENT_NAME;
	public String ORIGIN_EQUIPMENT_CODE;
	public String ORIGIN_EQUIPMENT_MODELNAME;
	
	//특이사항
	public int ORIGIN_UNIQUESS_ID;
	public String ORIGIN_UNIQUESS_CONTEXT;
	
	public int getORIGIN_EQUIPMENT_ID() {
		return ORIGIN_EQUIPMENT_ID;
	}
	public void setORIGIN_EQUIPMENT_ID(int oRIGIN_EQUIPMENT_ID) {
		ORIGIN_EQUIPMENT_ID = oRIGIN_EQUIPMENT_ID;
	}
	public String getORIGIN_EQUIPMENT_NAME() {
		return ORIGIN_EQUIPMENT_NAME;
	}
	public void setORIGIN_EQUIPMENT_NAME(String oRIGIN_EQUIPMENT_NAME) {
		ORIGIN_EQUIPMENT_NAME = oRIGIN_EQUIPMENT_NAME;
	}
	public String getORIGIN_EQUIPMENT_CODE() {
		return ORIGIN_EQUIPMENT_CODE;
	}
	public void setORIGIN_EQUIPMENT_CODE(String oRIGIN_EQUIPMENT_CODE) {
		ORIGIN_EQUIPMENT_CODE = oRIGIN_EQUIPMENT_CODE;
	}
	public String getORIGIN_EQUIPMENT_MODELNAME() {
		return ORIGIN_EQUIPMENT_MODELNAME;
	}
	public void setORIGIN_EQUIPMENT_MODELNAME(String oRIGIN_EQUIPMENT_MODELNAME) {
		ORIGIN_EQUIPMENT_MODELNAME = oRIGIN_EQUIPMENT_MODELNAME;
	}
	public int getORIGIN_UNIQUESS_ID() {
		return ORIGIN_UNIQUESS_ID;
	}
	public void setORIGIN_UNIQUESS_ID(int oRIGIN_UNIQUESS_ID) {
		ORIGIN_UNIQUESS_ID = oRIGIN_UNIQUESS_ID;
	}
	public String getORIGIN_UNIQUESS_CONTEXT() {
		return ORIGIN_UNIQUESS_CONTEXT;
	}
	public void setORIGIN_UNIQUESS_CONTEXT(String oRIGIN_UNIQUESS_CONTEXT) {
		ORIGIN_UNIQUESS_CONTEXT = oRIGIN_UNIQUESS_CONTEXT;
	}

	public String getORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY() {
		return ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public void setORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY(String oRIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY) {
		ORIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY = oRIGIN_PROCESS_SELF_INSPECTION_REPORT_DIRECTORY;
	}
	public int getORIGIN_PROCESS_OUTSOURCING_REGISTER() {
		return ORIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public void setORIGIN_PROCESS_OUTSOURCING_REGISTER(int oRIGIN_PROCESS_OUTSOURCING_REGISTER) {
		ORIGIN_PROCESS_OUTSOURCING_REGISTER = oRIGIN_PROCESS_OUTSOURCING_REGISTER;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NAME() {
		return ORIGIN_PROCESS_CUSTOMER_NAME;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NAME(String oRIGIN_PROCESS_CUSTOMER_NAME) {
		ORIGIN_PROCESS_CUSTOMER_NAME = oRIGIN_PROCESS_CUSTOMER_NAME;
	}
	public String getORIGIN_PROCESS_CUSTOMER_NUMBER() {
		return ORIGIN_PROCESS_CUSTOMER_NUMBER;
	}
	public void setORIGIN_PROCESS_CUSTOMER_NUMBER(String oRIGIN_PROCESS_CUSTOMER_NUMBER) {
		ORIGIN_PROCESS_CUSTOMER_NUMBER = oRIGIN_PROCESS_CUSTOMER_NUMBER;
	}

	public int getPROCESS_MAIN_CATEGORY_ID() {
		return PROCESS_MAIN_CATEGORY_ID;
	}
	public void setPROCESS_MAIN_CATEGORY_ID(int pROCESS_MAIN_CATEGORY_ID) {
		PROCESS_MAIN_CATEGORY_ID = pROCESS_MAIN_CATEGORY_ID;
	}
	public String getPROCESS_MAIN_CATEGORY_NAME() {
		return PROCESS_MAIN_CATEGORY_NAME;
	}
	public void setPROCESS_MAIN_CATEGORY_NAME(String pROCESS_MAIN_CATEGORY_NAME) {
		PROCESS_MAIN_CATEGORY_NAME = pROCESS_MAIN_CATEGORY_NAME;
	}
	public int getORIGIN_PROCESS_ID() {
		return ORIGIN_PROCESS_ID;
	}
	public void setORIGIN_PROCESS_ID(int oRIGIN_PROCESS_ID) {
		ORIGIN_PROCESS_ID = oRIGIN_PROCESS_ID;
	}
	public String getORIGIN_PROCESS_NAME() {
		return ORIGIN_PROCESS_NAME;
	}
	public void setORIGIN_PROCESS_NAME(String oRIGIN_PROCESS_NAME) {
		ORIGIN_PROCESS_NAME = oRIGIN_PROCESS_NAME;
	}
	public String getORIGIN_PROCESS_CODE() {
		return ORIGIN_PROCESS_CODE;
	}
	public void setORIGIN_PROCESS_CODE(String oRIGIN_PROCESS_CODE) {
		ORIGIN_PROCESS_CODE = oRIGIN_PROCESS_CODE;
	}
	public int getORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER() {
		return ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	public void setORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER(int oRIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER) {
		ORIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER = oRIGIN_PROCESS_SELF_INSPECTION_REPORT_REGISTER;
	}
	
}
